'use client';

import {
  Briefcase,
  Building2,
  CalendarCheck,
  CalendarRange,
  ClipboardCheck,
  ClipboardList,
  Clock,
  ListChecks,
  FileText,
  FileSpreadsheet,
  FolderKanban,
  Handshake,
  HardHat,
  Inbox,
  LayoutDashboard,
  Package,
  Receipt,
  RefreshCw,
  Repeat2,
  Settings,
  Timer,
  Upload,
  ShieldAlert,
  ShieldCheck,
  Truck,
  Users,
  Wallet,
  Wrench,
  ChartColumn,
  BadgeCheck,
  CalendarClock,
  Mail,
  Sparkles,
  Workflow,
  type LucideIcon,
} from 'lucide-react';
import type { NavIconKey } from './navigation';

const NAV_ICONS: Record<NavIconKey, LucideIcon> = {
  dashboard: LayoutDashboard,
  today: Inbox,
  projects: FolderKanban,
  jobs: Briefcase,
  expenses: Receipt,
  billing: Wallet,
  recurringDrafts: RefreshCw,
  changes: Repeat2,
  clients: Building2,
  vendors: Truck,
  workforce: Users,
  attendance: Clock,
  time: Timer,
  timesheets: ListChecks,
  documents: FileText,
  crm: Handshake,
  quotes: FileSpreadsheet,
  compliance: ShieldCheck,
  procurement: ClipboardList,
  materials: Package,
  fieldOps: HardHat,
  safety: ShieldAlert,
  forms: ClipboardCheck,
  assets: Wrench,
  reports: ChartColumn,
  approvals: BadgeCheck,
  monthClose: CalendarCheck,
  service: CalendarClock,
  scheduling: CalendarRange,
  imports: Upload,
  settings: Settings,
  cashFlow: Wallet,
  calendar: CalendarRange,
  warranty: ShieldCheck,
  communications: Mail,
  assistant: Sparkles,
  automations: Workflow,
  fieldHome: HardHat,
};

export function NavIcon({
  iconKey,
  className,
}: {
  iconKey: NavIconKey;
  className?: string;
}) {
  const Icon = NAV_ICONS[iconKey];
  return <Icon className={className} aria-hidden />;
}
