/**
 * Client-safe audit action catalog (string constants only).
 * Import from here in domain/UI modules - never from `@/shared/audit` (server/DB).
 */

export const AUDIT_ACTIONS = {
  ORGANIZATION_CREATED: 'organization.created',
  ORGANIZATION_UPDATED: 'organization.updated',
  MEMBERSHIP_CREATED: 'membership.created',
  MEMBERSHIP_UPDATED: 'membership.updated',
  MEMBERSHIP_REMOVED: 'membership.removed',
  ROLE_ASSIGNED: 'role.assigned',
  ROLE_PERMISSION_CHANGED: 'role.permission_changed',
  INVITATION_CREATED: 'invitation.created',
  INVITATION_ACCEPTED: 'invitation.accepted',
  INVITATION_REVOKED: 'invitation.revoked',
  SETTINGS_UPDATED: 'settings.updated',

  /** Organization branding / company identity (document letterhead — not UI theme). */
  COMPANY_PROFILE_UPDATED: 'branding.company_profile_updated',
  BRAND_PROFILE_CREATED: 'branding.brand_profile_created',
  BRAND_PROFILE_UPDATED: 'branding.brand_profile_updated',
  BRAND_PROFILE_ARCHIVED: 'branding.brand_profile_archived',
  BRAND_PROFILE_DEFAULT_SET: 'branding.brand_profile_default_set',
  BRAND_LOGO_CHANGED: 'branding.logo_changed',
  BRAND_SIGNATURE_CHANGED: 'branding.signature_changed',
  BRAND_STAMP_CHANGED: 'branding.stamp_changed',
  BRAND_LEGAL_TEXT_CHANGED: 'branding.legal_text_changed',

  PROJECT_CREATED: 'project.created',
  PROJECT_UPDATED: 'project.updated',
  PROJECT_ARCHIVED: 'project.archived',
  PROJECT_RESTORED: 'project.restored',
  PROJECT_TEMPLATE_APPLIED: 'project.template_applied',
  PROJECT_ACCESS_GRANTED: 'project_access.granted',
  PROJECT_ACCESS_REVOKED: 'project_access.revoked',
  WORK_PACKAGE_CREATED: 'work_package.created',
  WORK_PACKAGE_UPDATED: 'work_package.updated',
  WORK_PACKAGE_ARCHIVED: 'work_package.archived',
  PHASE_CREATED: 'phase.created',
  PHASE_UPDATED: 'phase.updated',
  PHASE_ARCHIVED: 'phase.archived',
  MILESTONE_CREATED: 'milestone.created',
  MILESTONE_UPDATED: 'milestone.updated',
  MILESTONE_ARCHIVED: 'milestone.archived',
  CONTRACT_VALUE_RECORDED: 'contract.value_recorded',
  CONTRACT_ADDITIONAL_CREATED: 'contract.additional_created',
  CONTRACT_UPDATED: 'contract.updated',

  CLIENT_CREATED: 'client.created',
  CLIENT_UPDATED: 'client.updated',
  CLIENT_ARCHIVED: 'client.archived',
  CLIENT_RESTORED: 'client.restored',
  CLIENT_CONTACT_CREATED: 'client_contact.created',
  CLIENT_CONTACT_UPDATED: 'client_contact.updated',
  CLIENT_CONTACT_DELETED: 'client_contact.deleted',
  CLIENT_CONTACT_MARKED_PRIMARY: 'client_contact.marked_primary',
  PARTY_IDENTIFIER_UPSERTED: 'party_identifier.upserted',
  PARTY_IDENTIFIER_DELETED: 'party_identifier.deleted',

  VENDOR_CREATED: 'vendor.created',
  VENDOR_UPDATED: 'vendor.updated',
  VENDOR_ARCHIVED: 'vendor.archived',
  VENDOR_RESTORED: 'vendor.restored',
  VENDOR_LINKED_FROM_EXPENSE: 'vendor.linked_from_expense',
  VENDOR_CONTACT_CREATED: 'vendor_contact.created',
  VENDOR_CONTACT_UPDATED: 'vendor_contact.updated',
  VENDOR_CONTACT_DELETED: 'vendor_contact.deleted',
  VENDOR_ENGAGEMENT_CREATED: 'vendor_engagement.created',
  VENDOR_ENGAGEMENT_ENDED: 'vendor_engagement.ended',
  VENDOR_ENGAGEMENT_CANCELLED: 'vendor_engagement.cancelled',
  VENDOR_ENGAGEMENT_ARCHIVED: 'vendor_engagement.archived',
  SUBCONTRACT_CREATED: 'subcontract.created',
  SUBCONTRACT_UPDATED: 'subcontract.updated',
  SUBCONTRACT_STATUS_CHANGED: 'subcontract.status_changed',
  SUBCONTRACT_VALUE_RECORDED: 'subcontract.value_recorded',
  SUBCONTRACT_DOCUMENT_LINKED: 'subcontract.document_linked',

  EXPENSE_CREATED: 'expense.created',
  EXPENSE_UPDATED: 'expense.updated',
  EXPENSE_FINALIZED: 'expense.finalized',
  EXPENSE_VOIDED: 'expense.voided',

  CHANGE_REQUEST_CREATED: 'change_request.created',
  CHANGE_REQUEST_UPDATED: 'change_request.updated',
  CHANGE_REQUEST_SUBMITTED: 'change_request.submitted',
  CHANGE_REQUEST_SENT: 'change_request.sent',
  CHANGE_REQUEST_REJECTED: 'change_request.rejected',
  CHANGE_REQUEST_CANCELLED: 'change_request.cancelled',
  CHANGE_REQUEST_APPROVED: 'change_request.approved',
  QUOTE_VERSION_CREATED: 'quote_version.created',
  QUOTE_VERSION_ISSUED: 'quote_version.issued',
  CHANGE_ORDER_CREATED: 'change_order.created',
  CHANGE_ORDER_REVERSED: 'change_order.reversed',

  BILLING_RECORD_CREATED: 'billing_record.created',
  BILLING_RECORD_UPDATED: 'billing_record.updated',
  BILLING_RECORD_FINALIZED: 'billing_record.finalized',
  BILLING_RECORD_VOIDED: 'billing_record.voided',
  BILLING_RECORD_ADJUSTMENT_CREATED: 'billing_record.adjustment_created',
  PAYMENT_RECORDED: 'payment.recorded',
  PAYMENT_VOIDED: 'payment.voided',

  EMPLOYEE_CREATED: 'employee.created',
  EMPLOYEE_UPDATED: 'employee.updated',
  EMPLOYEE_ARCHIVED: 'employee.archived',
  EMPLOYEE_RESTORED: 'employee.restored',
  RATE_VERSION_CREATED: 'rate_version.created',
  TIME_ENTRY_CREATED: 'time_entry.created',
  TIME_ENTRY_VOIDED: 'time_entry.voided',
  TIME_ENTRY_CORRECTED: 'time_entry.corrected',
  TIME_ENTRY_BULK_CREATED: 'time_entry.bulk_created',
  TIME_ENTRY_UPDATED: 'time_entry.updated',
  TIME_ENTRY_APPROVED: 'time_entry.approved',
  TIME_ENTRY_BULK_APPROVED: 'time_entry.bulk_approved',
  TIMESHEET_SUBMITTED: 'timesheet.submitted',
  TIMESHEET_RETURNED: 'timesheet.returned',
  TIMESHEET_APPROVED: 'timesheet.approved',
  PROJECT_TEAM_MEMBER_ADDED: 'project_team_member.added',
  PROJECT_TEAM_MEMBER_REMOVED: 'project_team_member.removed',
  ATTENDANCE_CLOCKED: 'attendance.clocked',
  ATTENDANCE_EVENT_RECORDED: 'attendance.event_recorded',
  ATTENDANCE_EVENT_VOIDED: 'attendance.event_voided',
  ATTENDANCE_EVENT_REPLACED: 'attendance.event_replaced',
  ATTENDANCE_DAY_VOIDED: 'attendance.day_voided',
  PROJECT_TEAM_ASSIGNMENT_UPDATED: 'project_team_assignment.updated',
  PROJECT_TEAM_ASSIGNMENT_CANCELLED: 'project_team_assignment.cancelled',

  DOCUMENT_UPLOADED: 'document.uploaded',
  DOCUMENT_FINALIZED: 'document.finalized',
  DOCUMENT_DELETED: 'document.deleted',
  DOCUMENT_STORAGE_CLEANUP_FAILED: 'document.storage_cleanup_failed',
  DOCUMENT_STORAGE_CLEANUP_COMPLETED: 'document.storage_cleanup_completed',

  CRM_PROSPECT_CREATED: 'crm.prospect_created',
  CRM_PROSPECT_UPDATED: 'crm.prospect_updated',
  CRM_LEAD_CREATED: 'crm.lead_created',
  CRM_LEAD_UPDATED: 'crm.lead_updated',
  CRM_OPPORTUNITY_CREATED: 'crm.opportunity_created',
  CRM_OPPORTUNITY_UPDATED: 'crm.opportunity_updated',
  CRM_OPPORTUNITY_NOTE_CREATED: 'crm.opportunity_note_created',
  CRM_OPPORTUNITY_CONVERTED: 'crm.opportunity_converted',
  CRM_ESTIMATE_CREATED: 'crm.estimate_created',
  CRM_ESTIMATE_UPDATED: 'crm.estimate_updated',
  CRM_SALES_QUOTE_CREATED: 'crm.sales_quote_created',
  CRM_SALES_QUOTE_VERSION_CREATED: 'crm.sales_quote_version_created',
  CRM_SALES_QUOTE_VERSION_ISSUED: 'crm.sales_quote_version_issued',
  CRM_QUOTE_ACCEPTED: 'crm.quote_accepted',

  COMPLIANCE_ARTIFACT_CREATED: 'compliance.artifact_created',
  COMPLIANCE_ARTIFACT_UPDATED: 'compliance.artifact_updated',

  PORTAL_GRANT_CREATED: 'portal.grant_created',
  PORTAL_GRANT_REVOKED: 'portal.grant_revoked',
  PORTAL_VENDOR_AP_CANDIDATE: 'portal.vendor_ap_candidate',
  PORTAL_VENDOR_COMPLIANCE_CANDIDATE: 'portal.vendor_compliance_candidate',
  PORTAL_VENDOR_CANDIDATE_REVIEWED: 'portal.vendor_candidate_reviewed',

  CUSTOM_FIELD_DEFINITION_CREATED: 'custom_field.definition_created',
  CUSTOM_FIELD_DEFINITION_UPDATED: 'custom_field.definition_updated',
  CUSTOM_FIELD_DEFINITION_ARCHIVED: 'custom_field.definition_archived',

  API_CLIENT_CREATED: 'api.client_created',
  API_KEY_CREATED: 'api.key_created',
  API_KEY_REVOKED: 'api.key_revoked',
  API_KEY_ROTATED: 'api.key_rotated',
  WEBHOOK_ENDPOINT_CREATED: 'api.webhook_created',
  WEBHOOK_ENDPOINT_REVOKED: 'api.webhook_revoked',
  WEBHOOK_SECRET_ROTATED: 'api.webhook_secret_rotated',
  WEBHOOK_DELIVERY_ENQUEUED: 'api.webhook_delivery_enqueued',

  MATERIAL_CREATED: 'material.created',
  MATERIAL_VENDOR_PRICE_CREATED: 'material_vendor_price.created',
  MATERIAL_VENDOR_PRICE_UPDATED: 'material_vendor_price.updated',
  MATERIAL_VENDOR_PRICE_DELETED: 'material_vendor_price.deleted',
  PROCUREMENT_RFQ_CREATED: 'procurement_rfq.created',
  PROCUREMENT_RFQ_STATUS_UPDATED: 'procurement_rfq.status_updated',
  SUPPLIER_QUOTE_CREATED: 'supplier_quote.created',
  SUPPLIER_QUOTE_STATUS_UPDATED: 'supplier_quote.status_updated',
  PURCHASE_ORDER_CREATED: 'purchase_order.created',
  PURCHASE_ORDER_ISSUED: 'purchase_order.issued',
  SUPPLIER_QUOTE_RECEIVED: 'procurement.supplier_quote_received',

  AP_BILL_CREATED: 'ap.bill_created',
  AP_BILL_VOIDED: 'ap.bill_voided',
  AP_MATCH_PROPOSED: 'ap.match_proposed',
  AP_MATCH_ACCEPTED: 'ap.match_accepted',
  AP_MATCH_REJECTED: 'ap.match_rejected',
  AP_PAYMENT_RECORDED: 'ap.payment_recorded',
  AP_PAYMENT_VOIDED: 'ap.payment_voided',
  AP_CREDIT_CREATED: 'ap.credit_created',
  AP_CREDIT_UPDATED: 'ap.credit_updated',
  AP_CREDIT_POSTED: 'ap.credit_posted',
  AP_CREDIT_APPLIED: 'ap.credit_applied',
  AP_CREDIT_VOIDED: 'ap.credit_voided',
  PURCHASE_ORDER_CANCELLED: 'purchase_order.cancelled',
  PURCHASE_ORDER_CLOSED: 'purchase_order.closed',
  PURCHASE_ORDER_RECEIVED: 'purchase_order.received',

  DAILY_LOG_CREATED: 'daily_log.created',
  DAILY_LOG_UPDATED: 'daily_log.updated',
  DAILY_LOG_SUBMITTED: 'daily_log.submitted',
  DAILY_LOG_FINALIZED: 'daily_log.finalized',
  DAILY_LOG_CORRECTION_ADDED: 'daily_log.correction_added',
  PUNCH_LIST_ITEM_CREATED: 'punch_list_item.created',
  PUNCH_LIST_ITEM_UPDATED: 'punch_list_item.updated',
  INSPECTION_CREATED: 'inspection.created',
  INSPECTION_UPDATED: 'inspection.updated',

  SAFETY_RECORD_CREATED: 'safety_record.created',
  SAFETY_RECORD_UPDATED: 'safety_record.updated',
  SAFETY_ACTION_CREATED: 'safety_action.created',
  SAFETY_ACTION_UPDATED: 'safety_action.updated',
  SAFETY_ATTENDEE_ADDED: 'safety_attendee.added',
  SAFETY_ATTENDEE_ACKNOWLEDGED: 'safety_attendee.acknowledged',

  ASSET_CREATED: 'asset.created',
  ASSET_UPDATED: 'asset.updated',
  FLEET_VEHICLE_CREATED: 'fleet_vehicle.created',
  FLEET_VEHICLE_UPDATED: 'fleet_vehicle.updated',
  MAINTENANCE_RECORD_CREATED: 'maintenance_record.created',
  MAINTENANCE_RECORD_UPDATED: 'maintenance_record.updated',
  INVENTORY_ITEM_CREATED: 'inventory_item.created',
  INVENTORY_MOVEMENT_RECORDED: 'inventory_movement.recorded',
  INVENTORY_LOCATION_CREATED: 'inventory_location.created',
  INVENTORY_LOCATION_UPDATED: 'inventory_location.updated',
  INVENTORY_LOCATION_ARCHIVED: 'inventory_location.archived',
  INVENTORY_RESERVED: 'inventory_reservation.created',
  INVENTORY_RESERVATION_RELEASED: 'inventory_reservation.released',
  INVENTORY_RESERVATION_CONSUMED: 'inventory_reservation.consumed',
  INVENTORY_COUNT_CREATED: 'inventory_count.created',
  INVENTORY_COUNT_FINALIZED: 'inventory_count.finalized',
  INVENTORY_COUNT_VOIDED: 'inventory_count.voided',
  MATERIAL_USAGE_RECORDED: 'material_usage.recorded',
  MATERIAL_USAGE_ARCHIVED: 'material_usage.archived',
  EQUIPMENT_USAGE_RECORDED: 'equipment_usage.recorded',
  EQUIPMENT_USAGE_ARCHIVED: 'equipment_usage.archived',

  TAX_RULE_CREATED: 'tax_rule.created',
  TAX_RULE_UPDATED: 'tax_rule.updated',

  /** Pre-sale estimates (`src/modules/quotes`) - not change-order / CRM / supplier quotes. */
  ESTIMATE_QUOTE_CREATED: 'estimate_quote.created',
  ESTIMATE_QUOTE_UPDATED: 'estimate_quote.updated',
  ESTIMATE_QUOTE_STATUS_CHANGED: 'estimate_quote.status_changed',
  ESTIMATE_QUOTE_CONVERTED: 'estimate_quote.converted',

  BUDGET_CREATED: 'budget.created',
  BUDGET_REVISED: 'budget.revised',
  BUDGET_ARCHIVED: 'budget.archived',

  APPROVAL_RULE_CREATED: 'approval_rule.created',
  APPROVAL_RULE_UPDATED: 'approval_rule.updated',
  APPROVAL_REQUEST_SUBMITTED: 'approval_request.submitted',
  APPROVAL_REQUEST_APPROVED: 'approval_request.approved',
  APPROVAL_REQUEST_REJECTED: 'approval_request.rejected',
  APPROVAL_REQUEST_CANCELLED: 'approval_request.cancelled',

  MONTH_CLOSE_PERIOD_OPENED: 'month_close.period_opened',
  MONTH_CLOSE_PERIOD_READY: 'month_close.period_ready',
  MONTH_CLOSE_PERIOD_REOPENED: 'month_close.period_reopened',
  MONTH_CLOSE_PERIOD_CLOSED: 'month_close.period_closed',
  MONTH_CLOSE_ADJUSTMENT_CREATED: 'month_close.adjustment_created',

  FORM_TEMPLATE_CREATED: 'form_template.created',
  FORM_TEMPLATE_UPDATED: 'form_template.updated',
  FORM_TEMPLATE_ARCHIVED: 'form_template.archived',
  FORM_SUBMISSION_CREATED: 'form_submission.created',
  FORM_SUBMISSION_UPDATED: 'form_submission.updated',
  FORM_SUBMISSION_SUBMITTED: 'form_submission.submitted',
  FORM_SUBMISSION_VOIDED: 'form_submission.voided',

  /** Service recurrence templates (`src/modules/service/recurrence`) - generate never finalizes money. */
  SERVICE_RECURRENCE_CREATED: 'service_recurrence.created',
  SERVICE_RECURRENCE_UPDATED: 'service_recurrence.updated',
  SERVICE_RECURRENCE_PAUSED: 'service_recurrence.paused',
  SERVICE_RECURRENCE_RESUMED: 'service_recurrence.resumed',
  SERVICE_RECURRENCE_ENDED: 'service_recurrence.ended',
  SERVICE_RECURRENCE_OCCURRENCE_SKIPPED: 'service_recurrence.occurrence_skipped',
  SERVICE_RECURRENCE_GENERATED: 'service_recurrence.generated',

  /** Retention / holdback release - cash timing only, never a second Actual. */
  RETENTION_RELEASED: 'retention.released',

  /** Recurring financial DRAFT templates - generate never finalizes or posts money. */
  RECURRING_FINANCIAL_DRAFT_CREATED: 'recurring_financial_draft.created',
  RECURRING_FINANCIAL_DRAFT_UPDATED: 'recurring_financial_draft.updated',
  RECURRING_FINANCIAL_DRAFT_PAUSED: 'recurring_financial_draft.paused',
  RECURRING_FINANCIAL_DRAFT_RESUMED: 'recurring_financial_draft.resumed',
  RECURRING_FINANCIAL_DRAFT_ENDED: 'recurring_financial_draft.ended',
  RECURRING_FINANCIAL_DRAFT_GENERATED: 'recurring_financial_draft.generated',

  /** Optional BOQ / progress / progress-billing vertical. */
  BOQ_CREATED: 'boq.created',
  BOQ_UPDATED: 'boq.updated',
  BOQ_ACTIVATED: 'boq.activated',
  BOQ_SUPERSEDED: 'boq.superseded',
  BOQ_ARCHIVED: 'boq.archived',
  BOQ_NODE_CREATED: 'boq_node.created',
  BOQ_NODE_UPDATED: 'boq_node.updated',
  BOQ_NODE_ARCHIVED: 'boq_node.archived',
  BOQ_IMPORTED: 'boq.imported',
  BOQ_CHANGE_ALLOCATED: 'boq_change.allocated',
  BOQ_PROGRESS_CREATED: 'boq_progress.created',
  BOQ_PROGRESS_UPDATED: 'boq_progress.updated',
  BOQ_PROGRESS_APPROVED: 'boq_progress.approved',
  BOQ_PROGRESS_SUPERSEDED: 'boq_progress.superseded',
  BOQ_PROGRESS_BILLING_CREATED: 'boq_progress.billing_created',
  BOQ_SUB_SCHEDULE_CREATED: 'boq_sub_schedule.created',
  BOQ_SUB_SCHEDULE_ACTIVATED: 'boq_sub_schedule.activated',
  BOQ_SUB_VALUATION_CREATED: 'boq_sub_valuation.created',
  BOQ_SUB_VALUATION_APPROVED: 'boq_sub_valuation.approved',
  BOQ_SUB_VALUATION_PROPOSED_AP: 'boq_sub_valuation.proposed_ap',
  BOQ_SUB_VALUATION_VOIDED: 'boq_sub_valuation.voided',

  CLOSEOUT_STARTED: 'closeout.started',
  CLOSEOUT_MARKED_READY: 'closeout.marked_ready',
  CLOSEOUT_CLOSED: 'closeout.closed',
  CLOSEOUT_REOPENED: 'closeout.reopened',

  WARRANTY_CREATED: 'warranty.created',
  WARRANTY_UPDATED: 'warranty.updated',
  WARRANTY_ISSUE_CREATED: 'warranty.issue_created',
  WARRANTY_ISSUE_RESOLVED: 'warranty.issue_resolved',

  COMMUNICATION_CREATED: 'communication.created',
  COMMUNICATION_QUEUED: 'communication.queued',
  COMMUNICATION_SENT: 'communication.sent',
  COMMUNICATION_FAILED: 'communication.failed',
  COMMUNICATION_CANCELLED: 'communication.cancelled',

  CALENDAR_EVENT_CREATED: 'calendar_event.created',
  CALENDAR_EVENT_UPDATED: 'calendar_event.updated',
  CALENDAR_EVENT_CANCELLED: 'calendar_event.cancelled',

  AUTOMATION_RULE_CREATED: 'automation_rule.created',
  AUTOMATION_RULE_UPDATED: 'automation_rule.updated',
  AUTOMATION_RULE_RAN: 'automation_rule.ran',

  ASSISTANT_CONVERSATION_CREATED: 'assistant.conversation_created',
} as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];

export const AUDIT_ACTION_VALUES = Object.values(AUDIT_ACTIONS) as readonly AuditAction[];
