"""One-off generator for material data feasibility research outputs. Research phase only."""
from __future__ import annotations

import csv
import json
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parent
GENERATED = datetime.now().isoformat(timespec="seconds")

SOURCES = [
    {
        "company_name": "Israel CBS — Residential Building Input Indices",
        "industry": "ALL / GOVERNMENT",
        "official_website": "https://www.cbs.gov.il/en/subjects/Pages/Price%20Index%20of%20Input%20in%20Residential%20Building.aspx",
        "source_type": "GOVERNMENT_INDEX",
        "current_price_data_available": "YES",
        "historical_price_data_available": "YES",
        "historical_range": "1990s–2026 (varies by sub-index; conductors API verified to 2025)",
        "update_frequency": "monthly",
        "format": "API, PDF, HTML",
        "contains_product_code": "YES",
        "contains_description": "YES",
        "contains_unit": "NO",
        "contains_price": "NO",
        "contains_effective_date": "YES",
        "price_type": "index (not unit price)",
        "requires_login": "NO",
        "free_access": "YES",
        "automation_feasibility": "HIGH",
        "historical_quality": "HIGH",
        "legal_access": "PUBLIC_FREE",
        "notes": "Free JSON API: https://api.cbs.gov.il/index/data/price?id={series_id}. Sub-indices cover electrical, plumbing, steel, cement, concrete, blocks.",
    },
    {
        "company_name": "ERCO (Arka) — B2C web shop",
        "industry": "ELECTRICAL",
        "official_website": "https://www.erco.co.il/",
        "source_type": "OFFICIAL_CATALOG_WITH_PRICES",
        "current_price_data_available": "YES",
        "historical_price_data_available": "NO",
        "historical_range": "current snapshot only (no public archive found)",
        "update_frequency": "irregular",
        "format": "HTML",
        "contains_product_code": "YES",
        "contains_description": "YES",
        "contains_unit": "YES",
        "contains_price": "YES",
        "contains_effective_date": "NO",
        "price_type": "retail/wholesale web list (incl. VAT shown)",
        "requires_login": "NO",
        "free_access": "YES",
        "automation_feasibility": "LOW",
        "historical_quality": "NONE",
        "legal_access": "UNCLEAR",
        "notes": "Product pages show SKU + unit price. PDF catalogs (cable trays, lighting) are technical, not price lists. No public downloadable contractor price list archive found via site search.",
    },
    {
        "company_name": "Golan / Pexgol — Residential systems price list",
        "industry": "PLUMBING",
        "official_website": "https://golanisrael.com/",
        "source_type": "OFFICIAL_PRICE_LIST",
        "current_price_data_available": "YES",
        "historical_price_data_available": "YES",
        "historical_range": "2022–2025 (sampled PDF versions)",
        "update_frequency": "irregular",
        "format": "PDF",
        "contains_product_code": "YES",
        "contains_description": "YES",
        "contains_unit": "YES",
        "contains_price": "YES",
        "contains_effective_date": "YES",
        "price_type": "list price ex-VAT",
        "requires_login": "NO",
        "free_access": "YES",
        "automation_feasibility": "MEDIUM",
        "historical_quality": "MEDIUM",
        "legal_access": "PUBLIC_FREE",
        "notes": "Strongest public supplier price-list series found for plumbing. Prices may change without notice per document disclaimer.",
    },
    {
        "company_name": "Golan / Pexgol — Infrastructure price list",
        "industry": "PLUMBING",
        "official_website": "https://golanisrael.com/",
        "source_type": "OFFICIAL_PRICE_LIST",
        "current_price_data_available": "YES",
        "historical_price_data_available": "PARTIAL",
        "historical_range": "2025 (sampled); residential series has deeper history",
        "update_frequency": "irregular",
        "format": "PDF",
        "contains_product_code": "YES",
        "contains_description": "YES",
        "contains_unit": "YES",
        "contains_price": "YES",
        "contains_effective_date": "YES",
        "price_type": "list price ex-VAT",
        "requires_login": "NO",
        "free_access": "YES",
        "automation_feasibility": "MEDIUM",
        "historical_quality": "LOW",
        "legal_access": "PUBLIC_FREE",
        "notes": "Large-diameter PE infrastructure pricing; some items quote-only.",
    },
    {
        "company_name": "Palgal — PE pipes price list (archived)",
        "industry": "PLUMBING",
        "official_website": "https://www.palgal.co.il/",
        "source_type": "OFFICIAL_PRICE_LIST",
        "current_price_data_available": "UNKNOWN",
        "historical_price_data_available": "YES",
        "historical_range": "2012 (archived PDF on site)",
        "update_frequency": "unknown",
        "format": "PDF",
        "contains_product_code": "YES",
        "contains_description": "YES",
        "contains_unit": "YES",
        "contains_price": "YES",
        "contains_effective_date": "YES",
        "price_type": "list price ex-VAT",
        "requires_login": "NO",
        "free_access": "YES",
        "automation_feasibility": "LOW",
        "historical_quality": "LOW",
        "legal_access": "PUBLIC_FREE",
        "notes": "Historical only; current public price list not verified in this research pass.",
    },
    {
        "company_name": "Plasson — Product catalogs",
        "industry": "PLUMBING",
        "official_website": "https://www.plasson.com/",
        "source_type": "CATALOG_NO_PRICES",
        "current_price_data_available": "NO",
        "historical_price_data_available": "NO",
        "historical_range": "N/A",
        "update_frequency": "irregular",
        "format": "PDF",
        "contains_product_code": "YES",
        "contains_description": "YES",
        "contains_unit": "YES",
        "contains_price": "NO",
        "contains_effective_date": "NO",
        "price_type": "unknown",
        "requires_login": "NO",
        "free_access": "YES",
        "automation_feasibility": "LOW",
        "historical_quality": "NONE",
        "legal_access": "PUBLIC_FREE",
        "notes": "Technical PDFs with product codes and specs; no public Israeli price list found.",
    },
    {
        "company_name": "Readymix (CEMEX Israel) — Product & price catalog",
        "industry": "CONCRETE/CEMENT",
        "official_website": "https://readymix.co.il/",
        "source_type": "OFFICIAL_CATALOG_WITH_PRICES",
        "current_price_data_available": "YES",
        "historical_price_data_available": "YES",
        "historical_range": "2023–2025 (web catalog editions)",
        "update_frequency": "annual",
        "format": "HTML",
        "contains_product_code": "YES",
        "contains_description": "YES",
        "contains_unit": "YES",
        "contains_price": "YES",
        "contains_effective_date": "YES",
        "price_type": "regional list / transport tables; concrete often project-specific",
        "requires_login": "NO",
        "free_access": "YES",
        "automation_feasibility": "MEDIUM",
        "historical_quality": "MEDIUM",
        "legal_access": "PUBLIC_FREE",
        "notes": "Regional delivery surcharges make national single price series difficult. Concrete unit prices often require quote.",
    },
    {
        "company_name": "Nesher — Cement products",
        "industry": "CONCRETE/CEMENT",
        "official_website": "https://www.nesher.co.il/",
        "source_type": "CATALOG_NO_PRICES",
        "current_price_data_available": "NO",
        "historical_price_data_available": "NO",
        "historical_range": "N/A",
        "update_frequency": "unknown",
        "format": "HTML",
        "contains_product_code": "YES",
        "contains_description": "YES",
        "contains_unit": "YES",
        "contains_price": "NO",
        "contains_effective_date": "NO",
        "price_type": "QUOTE_ONLY",
        "requires_login": "NO",
        "free_access": "YES",
        "automation_feasibility": "LOW",
        "historical_quality": "NONE",
        "legal_access": "PUBLIC_FREE",
        "notes": "Product specs published; pricing via customer service (*9409).",
    },
    {
        "company_name": "Ytong (Inrom) — AAC blocks",
        "industry": "BLOCKS/MASONRY",
        "official_website": "https://www.ytong.co.il/",
        "source_type": "CATALOG_NO_PRICES",
        "current_price_data_available": "NO",
        "historical_price_data_available": "NO",
        "historical_range": "N/A",
        "update_frequency": "unknown",
        "format": "HTML, PDF",
        "contains_product_code": "YES",
        "contains_description": "YES",
        "contains_unit": "YES",
        "contains_price": "NO",
        "contains_effective_date": "NO",
        "price_type": "QUOTE_ONLY",
        "requires_login": "NO",
        "free_access": "YES",
        "automation_feasibility": "LOW",
        "historical_quality": "NONE",
        "legal_access": "PUBLIC_FREE",
        "notes": "Manufacturer catalog/specs only. Third-party estimate pages exist but are not official supplier lists.",
    },
    {
        "company_name": "Klil — Aluminium window/door systems",
        "industry": "ALUMINIUM",
        "official_website": "https://www.klil.co.il/",
        "source_type": "CATALOG_NO_PRICES",
        "current_price_data_available": "NO",
        "historical_price_data_available": "NO",
        "historical_range": "N/A",
        "update_frequency": "annual",
        "format": "PDF, HTML",
        "contains_product_code": "YES",
        "contains_description": "YES",
        "contains_unit": "YES",
        "contains_price": "NO",
        "contains_effective_date": "NO",
        "price_type": "QUOTE_ONLY",
        "requires_login": "NO",
        "free_access": "YES",
        "automation_feasibility": "LOW",
        "historical_quality": "NONE",
        "legal_access": "PUBLIC_FREE",
        "notes": "Technical catalogs (4350, accessories). Purchase via authorized dealers; no public price list.",
    },
    {
        "company_name": "Extal — Aluminium facade/window systems",
        "industry": "ALUMINIUM",
        "official_website": "https://extal.com/",
        "source_type": "CATALOG_NO_PRICES",
        "current_price_data_available": "NO",
        "historical_price_data_available": "NO",
        "historical_range": "N/A",
        "update_frequency": "annual",
        "format": "PDF",
        "contains_product_code": "YES",
        "contains_description": "YES",
        "contains_unit": "YES",
        "contains_price": "NO",
        "contains_effective_date": "NO",
        "price_type": "QUOTE_ONLY",
        "requires_login": "NO",
        "free_access": "YES",
        "automation_feasibility": "LOW",
        "historical_quality": "NONE",
        "legal_access": "PUBLIC_FREE",
        "notes": "Catalog archive confirmed; pricing via authorized fabricators.",
    },
    {
        "company_name": "Israeli steel mills / distributors (general market)",
        "industry": "STEEL/REBAR",
        "official_website": "N/A — sector-wide",
        "source_type": "QUOTE_ONLY",
        "current_price_data_available": "PARTIAL",
        "historical_price_data_available": "NO",
        "historical_range": "N/A for public lists",
        "update_frequency": "weekly",
        "format": "other",
        "contains_product_code": "NO",
        "contains_description": "YES",
        "contains_unit": "YES",
        "contains_price": "PARTIAL",
        "contains_effective_date": "NO",
        "price_type": "contractor quote / market rumor",
        "requires_login": "NO",
        "free_access": "PARTIAL",
        "automation_feasibility": "LOW",
        "historical_quality": "NONE",
        "legal_access": "UNCLEAR",
        "notes": "No verified public official rebar price list PDF from major mills (Harel, Shoval, etc.). Trade press and reference sites publish indicative ton prices.",
    },
    {
        "company_name": "Metal Industries Association (PRIKO) — Metal price review",
        "industry": "STEEL/REBAR",
        "official_website": "https://industry.org.il/",
        "source_type": "PUBLIC_MARKET_DATA",
        "current_price_data_available": "YES",
        "historical_price_data_available": "PARTIAL",
        "historical_range": "2024 sampled; archive depth not fully mapped",
        "update_frequency": "monthly",
        "format": "PDF",
        "contains_product_code": "NO",
        "contains_description": "YES",
        "contains_unit": "YES",
        "contains_price": "YES",
        "contains_effective_date": "YES",
        "price_type": "market review / commodity benchmarks",
        "requires_login": "NO",
        "free_access": "YES",
        "automation_feasibility": "MEDIUM",
        "historical_quality": "MEDIUM",
        "legal_access": "PUBLIC_WITH_USAGE_LIMITS",
        "notes": "Association commodity review (copper, aluminium, steel proxies). Not a supplier SKU price list.",
    },
    {
        "company_name": "Dekel — Construction & infrastructure price book",
        "industry": "ALL",
        "official_website": "https://www.dekel.co.il/",
        "source_type": "PAID",
        "current_price_data_available": "YES",
        "historical_price_data_available": "YES",
        "historical_range": "multi-year (paid product)",
        "update_frequency": "monthly",
        "format": "other",
        "contains_product_code": "YES",
        "contains_description": "YES",
        "contains_unit": "YES",
        "contains_price": "YES",
        "contains_effective_date": "YES",
        "price_type": "professional reference / market estimate",
        "requires_login": "YES",
        "free_access": "NO",
        "automation_feasibility": "LOW",
        "historical_quality": "HIGH",
        "legal_access": "PAID_LICENSE",
        "notes": "Excluded from V1 free-data scope per project rules. Mentioned as industry benchmark only.",
    },
    {
        "company_name": "CivilEng — Raw materials reference table",
        "industry": "ALL",
        "official_website": "https://www.civileng.co.il/",
        "source_type": "PUBLIC_MARKET_DATA",
        "current_price_data_available": "YES",
        "historical_price_data_available": "NO",
        "historical_range": "current reference page only",
        "update_frequency": "unknown",
        "format": "HTML",
        "contains_product_code": "NO",
        "contains_description": "YES",
        "contains_unit": "YES",
        "contains_price": "YES",
        "contains_effective_date": "NO",
        "price_type": "reference estimate",
        "requires_login": "NO",
        "free_access": "YES",
        "automation_feasibility": "LOW",
        "historical_quality": "LOW",
        "legal_access": "PUBLIC_WITH_USAGE_LIMITS",
        "notes": "Useful sanity-check reference for rebar, concrete, cement bag — not auditable supplier list.",
    },
    {
        "company_name": "Gilar (Sika Israel) — Waterproofing catalog",
        "industry": "WATERPROOFING/CHEMICALS",
        "official_website": "https://gilar.co.il/",
        "source_type": "CATALOG_NO_PRICES",
        "current_price_data_available": "NO",
        "historical_price_data_available": "NO",
        "historical_range": "N/A",
        "update_frequency": "annual",
        "format": "PDF, HTML",
        "contains_product_code": "YES",
        "contains_description": "YES",
        "contains_unit": "PARTIAL",
        "contains_price": "NO",
        "contains_effective_date": "NO",
        "price_type": "QUOTE_ONLY",
        "requires_login": "NO",
        "free_access": "YES",
        "automation_feasibility": "LOW",
        "historical_quality": "NONE",
        "legal_access": "PUBLIC_FREE",
        "notes": "2026 interactive catalog downloadable; no public price list.",
    },
    {
        "company_name": "Knauf Israel — Gypsum boards",
        "industry": "GYPSUM/INSULATION",
        "official_website": "https://knauf.com/he-IL",
        "source_type": "CATALOG_NO_PRICES",
        "current_price_data_available": "NO",
        "historical_price_data_available": "NO",
        "historical_range": "N/A",
        "update_frequency": "annual",
        "format": "PDF, HTML",
        "contains_product_code": "YES",
        "contains_description": "YES",
        "contains_unit": "YES",
        "contains_price": "NO",
        "contains_effective_date": "NO",
        "price_type": "QUOTE_ONLY",
        "requires_login": "NO",
        "free_access": "YES",
        "automation_feasibility": "LOW",
        "historical_quality": "NONE",
        "legal_access": "PUBLIC_FREE",
        "notes": "Rich SKU catalog with material numbers; distributor pricing only.",
    },
    {
        "company_name": "Meitav-Tec — Controls/thermostats price list",
        "industry": "ELECTRICAL",
        "official_website": "https://meitavtec.co.il/",
        "source_type": "OFFICIAL_PRICE_LIST",
        "current_price_data_available": "YES",
        "historical_price_data_available": "PARTIAL",
        "historical_range": "2024 PDF verified; 2022–2023 not found in public downloads",
        "update_frequency": "annual",
        "format": "PDF, HTML",
        "contains_product_code": "YES",
        "contains_description": "YES",
        "contains_unit": "YES",
        "contains_price": "YES",
        "contains_effective_date": "YES",
        "price_type": "list price",
        "requires_login": "NO",
        "free_access": "YES",
        "automation_feasibility": "MEDIUM",
        "historical_quality": "LOW",
        "legal_access": "PUBLIC_FREE",
        "notes": "Narrow product family (HVAC controls), not general wire/cable pricing.",
    },
    {
        "company_name": "Uriel Shay — Electrical tools catalog",
        "industry": "ELECTRICAL",
        "official_website": "https://www.uriel-shay.com/",
        "source_type": "CATALOG_NO_PRICES",
        "current_price_data_available": "UNKNOWN",
        "historical_price_data_available": "NO",
        "historical_range": "2023/24 catalog sampled — pricing not verified in catalog",
        "update_frequency": "annual",
        "format": "PDF",
        "contains_product_code": "YES",
        "contains_description": "YES",
        "contains_unit": "PARTIAL",
        "contains_price": "NO",
        "contains_effective_date": "NO",
        "price_type": "unknown",
        "requires_login": "NO",
        "free_access": "YES",
        "automation_feasibility": "LOW",
        "historical_quality": "NONE",
        "legal_access": "PUBLIC_FREE",
        "notes": "Major wholesaler catalog; public price list not confirmed in sampled PDF.",
    },
    {
        "company_name": "Owner invoice archive (ERCO) — private purchase history",
        "industry": "ELECTRICAL",
        "official_website": "N/A — internal dataset",
        "source_type": "PUBLIC_MARKET_DATA",
        "current_price_data_available": "YES",
        "historical_price_data_available": "YES",
        "historical_range": "2016–2026 (project-specific extraction)",
        "update_frequency": "irregular",
        "format": "CSV",
        "contains_product_code": "YES",
        "contains_description": "YES",
        "contains_unit": "YES",
        "contains_price": "YES",
        "contains_effective_date": "YES",
        "price_type": "actual paid invoice net/gross",
        "requires_login": "NO",
        "free_access": "YES",
        "automation_feasibility": "MEDIUM",
        "historical_quality": "MEDIUM",
        "legal_access": "PUBLIC_FREE",
        "notes": "Not a public market feed — single-supplier purchase-driven series. Valuable for internal benchmarking only.",
    },
]

PRICE_LISTS = [
    {
        "company": "Golan / Pexgol",
        "document_title": "מחירון מערכות גולן דירתי",
        "effective_date": "2024-01",
        "year": 2024,
        "format": "PDF",
        "public_url": "https://golanisrael.com/wp-content/uploads/2024/08/800-111-mehiron_dirati_38_biz.pdf",
        "historical_versions_found": "YES",
        "number_of_versions_found": 3,
        "notes": "Also found Mar-2022 update PDF on same domain.",
    },
    {
        "company": "Golan / Pexgol",
        "document_title": "מחירון מערכות גולן דירתי — עדכון",
        "effective_date": "2022-03-01",
        "year": 2022,
        "format": "PDF",
        "public_url": "https://golanisrael.com/wp-content/uploads/2022/03/800-111-mehiron_dirati_idkun_merch_2022_02_mail.pdf",
        "historical_versions_found": "YES",
        "number_of_versions_found": 3,
        "notes": "Confirms continuity 2022→2024.",
    },
    {
        "company": "Golan / Pexgol",
        "document_title": "מחירון פקסגול תשתיות",
        "effective_date": "2025-04",
        "year": 2025,
        "format": "PDF",
        "public_url": "https://golanisrael.com/wp-content/uploads/2025/04/800-7916613072-Mehiron_Tashtiyot_02_biz_mail.pdf",
        "historical_versions_found": "PARTIAL",
        "number_of_versions_found": 1,
        "notes": "Infrastructure PE pricing.",
    },
    {
        "company": "Palgal",
        "document_title": "PE pipes price list May 2012",
        "effective_date": "2012-05",
        "year": 2012,
        "format": "PDF",
        "public_url": "https://www.palgal.co.il/PalGal/userdata/SendFile.asp?DBID=1&GID=110&LNGID=2",
        "historical_versions_found": "YES",
        "number_of_versions_found": 1,
        "notes": "Archived; current list not verified.",
    },
    {
        "company": "Readymix (CEMEX Israel)",
        "document_title": "קטלוג מוצרים ומחירים 2025",
        "effective_date": "2025",
        "year": 2025,
        "format": "HTML",
        "public_url": "https://readymix.co.il/wp-content/themes/readymix/catalogs/readymix2025/",
        "historical_versions_found": "YES",
        "number_of_versions_found": 2,
        "notes": "2023 edition also public on same path pattern.",
    },
    {
        "company": "Readymix (CEMEX Israel)",
        "document_title": "קטלוג מוצרים ומחירים 2023",
        "effective_date": "2023",
        "year": 2023,
        "format": "HTML",
        "public_url": "https://readymix.co.il/wp-content/themes/readymix/catalogs/readymix2023/",
        "historical_versions_found": "YES",
        "number_of_versions_found": 2,
        "notes": "Regional transport pricing tables included.",
    },
    {
        "company": "Meitav-Tec",
        "document_title": "מחירון מיטב-טק 2024",
        "effective_date": "2024-01",
        "year": 2024,
        "format": "PDF",
        "public_url": "https://meitavtec.co.il/download/%D7%9E%D7%97%D7%99%D7%A8%D7%95%D7%9F%20%D7%9E%D7%99%D7%98%D7%91-%D7%98%D7%A7%202024.pdf",
        "historical_versions_found": "PARTIAL",
        "number_of_versions_found": 1,
        "notes": "HVAC controls only.",
    },
    {
        "company": "Metal Industries Association",
        "document_title": "סקירת מחירי מתכות 12/2024",
        "effective_date": "2024-12",
        "year": 2024,
        "format": "PDF",
        "public_url": "https://industry.org.il/files/metal/priko/PRIKO2024/%D7%A1%D7%A7%D7%99%D7%A8%D7%AA%20%D7%9E%D7%97%D7%99%D7%A8%D7%99%20%D7%9E%D7%AA%D7%9B%D7%95%D7%AA%2005_12_2024.pdf",
        "historical_versions_found": "PARTIAL",
        "number_of_versions_found": 1,
        "notes": "Commodity review, not SKU list.",
    },
]

GOV_INDICES = [
    {"series_id": "200010", "series_name": "Price index of input in residential building — general", "trade": "ALL", "frequency": "monthly", "historical_range": "2018–2026 (verified via prior load); longer via API", "api_available": "YES", "free": "YES", "automation_feasibility": "HIGH", "url": "https://api.cbs.gov.il/index/data/price?id=200010"},
    {"series_id": "201140", "series_name": "Cement", "trade": "CONCRETE/CEMENT", "frequency": "monthly", "historical_range": "long (CBS chapter c)", "api_available": "YES", "free": "YES", "automation_feasibility": "HIGH", "url": "https://api.cbs.gov.il/index/data/price?id=201140"},
    {"series_id": "201160", "series_name": "Ready-mixed concrete", "trade": "CONCRETE/CEMENT", "frequency": "monthly", "historical_range": "long (CBS chapter c)", "api_available": "YES", "free": "YES", "automation_feasibility": "HIGH", "url": "https://api.cbs.gov.il/index/data/price?id=201160"},
    {"series_id": "201130", "series_name": "Cement, ytong and their products", "trade": "BLOCKS/MASONRY", "frequency": "monthly", "historical_range": "long (CBS chapter c)", "api_available": "YES", "free": "YES", "automation_feasibility": "HIGH", "url": "https://api.cbs.gov.il/index/data/price?id=201130"},
    {"series_id": "201230", "series_name": "Rebar (building steel)", "trade": "STEEL/REBAR", "frequency": "monthly", "historical_range": "long — verified to Aug-2026", "api_available": "YES", "free": "YES", "automation_feasibility": "HIGH", "url": "https://api.cbs.gov.il/index/data/price?id=201230"},
    {"series_id": "201260", "series_name": "Steel mesh", "trade": "STEEL/REBAR", "frequency": "monthly", "historical_range": "long (CBS chapter c)", "api_available": "YES", "free": "YES", "automation_feasibility": "HIGH", "url": "https://api.cbs.gov.il/index/data/price?id=201260"},
    {"series_id": "201210", "series_name": "Iron and metal products", "trade": "STEEL/REBAR", "frequency": "monthly", "historical_range": "long (CBS chapter c)", "api_available": "YES", "free": "YES", "automation_feasibility": "HIGH", "url": "https://api.cbs.gov.il/index/data/price?id=201210"},
    {"series_id": "201320", "series_name": "Products and accessories for electrical work", "trade": "ELECTRICAL", "frequency": "monthly", "historical_range": "long (CBS chapter c)", "api_available": "YES", "free": "YES", "automation_feasibility": "HIGH", "url": "https://api.cbs.gov.il/index/data/price?id=201320"},
    {"series_id": "201330", "series_name": "Pipes for electrical installation", "trade": "ELECTRICAL", "frequency": "monthly", "historical_range": "long (CBS chapter c)", "api_available": "YES", "free": "YES", "automation_feasibility": "HIGH", "url": "https://api.cbs.gov.il/index/data/price?id=201330"},
    {"series_id": "201340", "series_name": "Conductors (copper cable proxy)", "trade": "ELECTRICAL", "frequency": "monthly", "historical_range": "verified to Jul-2025 via API", "api_available": "YES", "free": "YES", "automation_feasibility": "HIGH", "url": "https://api.cbs.gov.il/index/data/price?id=201340"},
    {"series_id": "201380", "series_name": "Products and accessories for sanitary plumbing work", "trade": "PLUMBING", "frequency": "monthly", "historical_range": "long (CBS chapter c)", "api_available": "YES", "free": "YES", "automation_feasibility": "HIGH", "url": "https://api.cbs.gov.il/index/data/price?id=201380"},
    {"series_id": "201400", "series_name": "Plastic pipes", "trade": "PLUMBING", "frequency": "monthly", "historical_range": "long (CBS chapter c)", "api_available": "YES", "free": "YES", "automation_feasibility": "HIGH", "url": "https://api.cbs.gov.il/index/data/price?id=201400"},
    {"series_id": "chapter_ca", "series_name": "Price index of input in commercial and office building", "trade": "ALL", "frequency": "monthly", "historical_range": "long (CBS chapter ca)", "api_available": "YES", "free": "YES", "automation_feasibility": "HIGH", "url": "https://api.cbs.gov.il/index/catalog/chapter?id=ca&lang=en"},
    {"series_id": "chapter_d", "series_name": "Price indices of input in road construction and bridging", "trade": "ALL", "frequency": "monthly", "historical_range": "long (CBS chapter d)", "api_available": "YES", "free": "YES", "automation_feasibility": "HIGH", "url": "https://api.cbs.gov.il/index/catalog/chapter?id=d&lang=en"},
]

GLOBAL_DRIVERS = [
    {"driver": "COPPER_USD", "trades": "ELECTRICAL", "free_source": "FRED", "series_id": "PCOPPUSDM", "frequency": "monthly", "history": "1990s–2026", "api_download": "YES", "url": "https://fred.stlouisfed.org/series/PCOPPUSDM"},
    {"driver": "ALUMINIUM_USD", "trades": "ELECTRICAL, ALUMINIUM", "free_source": "FRED/IMF", "series_id": "PALUMUSDM", "frequency": "monthly", "history": "1990s–2026", "api_download": "YES", "url": "https://fred.stlouisfed.org/series/PALUMUSDM"},
    {"driver": "USD_ILS", "trades": "ALL", "free_source": "FRED/OECD", "series_id": "CCUSMA02ILM618N", "frequency": "monthly", "history": "1990s–2026", "api_download": "YES", "url": "https://fred.stlouisfed.org/series/CCUSMA02ILM618N"},
    {"driver": "USD_ILS_DAILY", "trades": "ALL", "free_source": "Bank of Israel SDMX", "series_id": "RER_USD_ILS", "frequency": "daily", "history": "2008–2026", "api_download": "YES", "url": "https://edge.boi.gov.il/FusionEdgeServer/sdmx/v2/data/dataflow/BOI.STATISTICS/EXR/1.0/RER_USD_ILS?format=csv"},
    {"driver": "BRENT_OIL", "trades": "ALL", "free_source": "FRED/IMF", "series_id": "POILBREUSDM", "frequency": "monthly", "history": "1990s–2026", "api_download": "YES", "url": "https://fred.stlouisfed.org/series/POILBREUSDM"},
    {"driver": "IRON_ORE", "trades": "STEEL/REBAR", "free_source": "FRED/IMF", "series_id": "PIORECRUSDM", "frequency": "monthly", "history": "1992–2026", "api_download": "YES", "url": "https://fred.stlouisfed.org/series/PIORECRUSDM"},
    {"driver": "STEEL_SCRAP", "trades": "STEEL/REBAR", "free_source": "FRED/BLS PPI", "series_id": "WPS101211", "frequency": "monthly", "history": "1980s–2026", "api_download": "YES", "url": "https://fred.stlouisfed.org/series/WPS101211"},
    {"driver": "HRC_STEEL", "trades": "STEEL/REBAR", "free_source": "FRED/BLS PPI", "series_id": "WPS101704", "frequency": "monthly", "history": "1980s–2026", "api_download": "YES", "url": "https://fred.stlouisfed.org/series/WPS101704"},
    {"driver": "PVC_POLYMER_PROXY", "trades": "PLUMBING, ELECTRICAL", "free_source": "FRED (proxy — verify series fit)", "series_id": "WPU063801", "frequency": "monthly", "history": "long", "api_download": "YES", "url": "https://fred.stlouisfed.org/series/WPU063801", "notes": "US PPI plastics proxy; not Israeli PVC spot."},
    {"driver": "NATURAL_GAS_EU_PROXY", "trades": "CONCRETE/CEMENT, ALUMINIUM", "free_source": "FRED/World Bank", "series_id": "PNGASEUUSDM", "frequency": "monthly", "history": "long", "api_download": "YES", "url": "https://fred.stlouisfed.org/series/PNGASEUUSDM", "notes": "Energy input proxy only."},
    {"driver": "ISRAEL_CONSTRUCTION_INPUT", "trades": "ALL", "free_source": "Israel CBS", "series_id": "200010", "frequency": "monthly", "history": "2018–2026 verified", "api_download": "YES", "url": "https://api.cbs.gov.il/index/data/price?id=200010", "notes": "Government index — not supplier price."},
]

TRADES = [
    {"trade": "ELECTRICAL", "local_price_data_score": 2, "historical_depth_score": 3, "update_frequency_score": 3, "automation_score": 3, "external_driver_score": 5, "total_score": 16, "tier": "GOOD", "buildable_level": "LEVEL 3", "public_official_price_lists": "PARTIAL (ERCO web current; Meitav-Tec narrow PDF; no broad wire/cable public list series)", "historical_depth": "MEDIUM (CBS 201340 conductors + owner invoices)", "free_automation": "CBS+FRED HIGH; supplier web LOW", "best_local_source": "CBS 201340 + owner ERCO invoice history", "best_external_drivers": "Copper USD, Aluminium USD, USD/ILS, Brent, CBS electrical sub-index"},
    {"trade": "PLUMBING", "local_price_data_score": 4, "historical_depth_score": 4, "update_frequency_score": 3, "automation_score": 2, "external_driver_score": 4, "total_score": 17, "tier": "GOOD", "buildable_level": "LEVEL 3", "public_official_price_lists": "YES — Golan/Pexgol PDF price lists (2022–2025 sampled)", "historical_depth": "GOOD for Pexgol residential series", "free_automation": "PDF parsing MEDIUM; CBS 201380/201400 HIGH", "best_local_source": "Golan/Pexgol official PDF price lists", "best_external_drivers": "Oil/Brent, USD/ILS, polymer PPI proxy, CBS plumbing indices"},
    {"trade": "ALUMINIUM", "local_price_data_score": 1, "historical_depth_score": 2, "update_frequency_score": 2, "automation_score": 3, "external_driver_score": 5, "total_score": 13, "tier": "PARTIAL", "buildable_level": "LEVEL 1", "public_official_price_lists": "NO — Klil/Extal catalogs only (quote-only pricing)", "historical_depth": "LOW local; CBS metals group indirect", "free_automation": "FRED aluminium HIGH; local NONE", "best_local_source": "None public — quote via authorized fabricators", "best_external_drivers": "Aluminium USD, USD/ILS, energy proxies"},
    {"trade": "STEEL/REBAR", "local_price_data_score": 2, "historical_depth_score": 4, "update_frequency_score": 3, "automation_score": 4, "external_driver_score": 5, "total_score": 18, "tier": "GOOD", "buildable_level": "LEVEL 2", "public_official_price_lists": "NO official mill list; PRIKO commodity review + CBS index", "historical_depth": "HIGH via CBS 201230/201260", "free_automation": "CBS+FRED HIGH", "best_local_source": "CBS rebar index 201230 + PRIKO metal review PDF", "best_external_drivers": "Iron ore, scrap PPI, HRC PPI, USD/ILS, Brent"},
    {"trade": "CONCRETE/CEMENT", "local_price_data_score": 3, "historical_depth_score": 3, "update_frequency_score": 2, "automation_score": 2, "external_driver_score": 4, "total_score": 14, "tier": "PARTIAL", "buildable_level": "LEVEL 2", "public_official_price_lists": "PARTIAL — Readymix regional catalog 2023/2025; Nesher quote-only", "historical_depth": "MEDIUM (Readymix 2 editions + CBS cement/concrete)", "free_automation": "CBS HIGH; Readymix HTML MEDIUM", "best_local_source": "CBS 201140/201160 + Readymix regional catalog", "best_external_drivers": "Energy/gas proxy, CBS construction input, transport/wage indices"},
    {"trade": "BLOCKS/MASONRY", "local_price_data_score": 2, "historical_depth_score": 2, "update_frequency_score": 2, "automation_score": 2, "external_driver_score": 3, "total_score": 11, "tier": "PARTIAL", "buildable_level": "LEVEL 2", "public_official_price_lists": "NO from Ytong; reference tables on architect sites only", "historical_depth": "LOW supplier; CBS 201130 ytong group", "free_automation": "CBS MEDIUM", "best_local_source": "CBS 201130 cement/ytong products index", "best_external_drivers": "Cement/energy/CBS general construction"},
    {"trade": "WATERPROOFING/CHEMICALS", "local_price_data_score": 1, "historical_depth_score": 1, "update_frequency_score": 2, "automation_score": 1, "external_driver_score": 3, "total_score": 8, "tier": "WEAK", "buildable_level": "LEVEL 1", "public_official_price_lists": "NO — Gilar/Sika catalog without prices", "historical_depth": "NONE public", "free_automation": "LOW", "best_local_source": "None verified free", "best_external_drivers": "Bitumen/oil proxy, CBS miscellaneous materials (weak)"},
    {"trade": "GYPSUM/INSULATION", "local_price_data_score": 1, "historical_depth_score": 2, "update_frequency_score": 2, "automation_score": 2, "external_driver_score": 3, "total_score": 10, "tier": "WEAK", "buildable_level": "LEVEL 1", "public_official_price_lists": "NO — Knauf SKU catalog without public prices", "historical_depth": "LOW", "free_automation": "LOW local; CBS indirect", "best_local_source": "Knauf catalog for SKU mapping only", "best_external_drivers": "Energy, gypsum/paper proxies weak; CBS finished products"},
]


def write_csv(path: Path, rows: list[dict]) -> None:
    if not rows:
        return
    fieldnames: list[str] = []
    seen: set[str] = set()
    for row in rows:
        for key in row:
            if key not in seen:
                seen.add(key)
                fieldnames.append(key)
    with path.open("w", newline="", encoding="utf-8-sig") as f:
        w = csv.DictWriter(f, fieldnames=fieldnames, extrasaction="ignore")
        w.writeheader()
        w.writerows(rows)


def main() -> None:
    write_csv(ROOT / "material_price_sources.csv", SOURCES)
    write_csv(ROOT / "official_price_lists.csv", PRICE_LISTS)
    write_csv(ROOT / "government_indices.csv", GOV_INDICES)
    write_csv(ROOT / "global_driver_sources.csv", GLOBAL_DRIVERS)
    write_csv(ROOT / "trade_feasibility_matrix.csv", TRADES)

    report = {
        "generated_at": GENERATED,
        "research_mode": "FEASIBILITY_ONLY",
        "no_product_built": True,
        "no_projectflow_changes": True,
        "totals": {
            "official_supplier_sources_found": len([s for s in SOURCES if s["source_type"] in ("OFFICIAL_PRICE_LIST", "OFFICIAL_CATALOG_WITH_PRICES")]),
            "historical_price_list_series_found": len([p for p in PRICE_LISTS if p["historical_versions_found"] in ("YES", "PARTIAL")]),
            "government_series_found": len(GOV_INDICES),
            "free_global_driver_series_found": len(GLOBAL_DRIVERS),
        },
        "multi_trade_monitor_feasible": "YES",
        "reliable_30_60_90_forecasts_today": "PARTIAL",
        "missing_for_reliable_forecasts": [
            "Broad public historical SKU price lists for electrical wire/cable (only current web + private invoices)",
            "Official mill/distributor rebar price lists (CBS index exists but is not buy-price)",
            "Aluminium/waterproofing/gypsum supplier list prices",
            "Continuous automated history for PDF price lists (Golan, Readymix)",
            "Sufficient out-of-sample proof that commodity rules predict supplier prices (prior backtest: INCONCLUSIVE)",
        ],
        "recommended_v1_scope": "Multi-trade MARKET PRESSURE monitor using CBS sub-indices + FRED/BOI drivers; add Golan Pexgol PDF index for plumbing; optional internal ERCO invoice index for electrical only.",
        "best_3_trades_first": ["STEEL/REBAR", "PLUMBING", "ELECTRICAL"],
        "trades_not_worth_building_yet": ["WATERPROOFING/CHEMICALS", "GYPSUM/INSULATION", "ALUMINIUM (product-level)"],
        "trades": {t["trade"]: t for t in TRADES},
    }
    (ROOT / "material_data_feasibility_report.json").write_text(
        json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8"
    )
    print("Wrote research outputs to", ROOT)


if __name__ == "__main__":
    main()
