import { NextResponse, type NextRequest } from 'next/server';
import { createSupabaseServerClient, isSupabaseConfigured } from '@/shared/supabase/server';
import { DEFAULT_LOCALE } from '@/shared/i18n/config';

/**
 * Exchanges the one-time code from a confirmation or reset email for a session.
 * Locale-agnostic on purpose: the link is generated by Supabase, so it cannot
 * carry our locale prefix.
 */
export async function GET(request: NextRequest) {
  const { searchParams, origin } = request.nextUrl;
  const code = searchParams.get('code');
  const next = searchParams.get('next') ?? '/';
  const locale = searchParams.get('locale') ?? DEFAULT_LOCALE;

  if (!code || !isSupabaseConfigured()) {
    return NextResponse.redirect(`${origin}/${locale}/sign-in?error=auth-callback`);
  }

  const supabase = await createSupabaseServerClient();
  const { error } = await supabase.auth.exchangeCodeForSession(code);

  if (error) {
    return NextResponse.redirect(`${origin}/${locale}/sign-in?error=auth-callback`);
  }

  return NextResponse.redirect(`${origin}/${locale}${next === '/' ? '' : next}`);
}
