/** Domain event types for the 'subcontract' track. Shape: <domain>.<entity>.<verb> (3+ lowercase segments). */
export const SUBCONTRACT_DOMAIN_EVENTS = {
  SUBCONTRACT_AGREEMENT_CREATED: 'subcontract.agreement.created',
  SUBCONTRACT_AGREEMENT_UPDATED: 'subcontract.agreement.updated',
  SUBCONTRACT_AGREEMENT_ACTIVATED: 'subcontract.agreement.activated',
  SUBCONTRACT_AGREEMENT_SUSPENDED: 'subcontract.agreement.suspended',
  SUBCONTRACT_AGREEMENT_RESUMED: 'subcontract.agreement.resumed',
  SUBCONTRACT_AGREEMENT_COMPLETED: 'subcontract.agreement.completed',
  SUBCONTRACT_AGREEMENT_CLOSED: 'subcontract.agreement.closed',
  SUBCONTRACT_AGREEMENT_CANCELLED: 'subcontract.agreement.cancelled',
  SUBCONTRACT_WORK_LINE_ADDED: 'subcontract.work_line.added',
  SUBCONTRACT_WORK_LINE_UPDATED: 'subcontract.work_line.updated',
  SUBCONTRACT_WORK_LINE_ARCHIVED: 'subcontract.work_line.archived',
  SUBCONTRACT_CHANGE_CREATED: 'subcontract.change.created',
  SUBCONTRACT_CHANGE_SUBMITTED: 'subcontract.change.submitted',
  SUBCONTRACT_CHANGE_VERSION_PROPOSED: 'subcontract.change.version_proposed',
  SUBCONTRACT_CHANGE_APPROVED: 'subcontract.change.approved',
  SUBCONTRACT_CHANGE_REJECTED: 'subcontract.change.rejected',
  SUBCONTRACT_CHANGE_WITHDRAWN: 'subcontract.change.withdrawn',
  SUBCONTRACT_UNPRICED_WORK_RECORDED: 'subcontract.unpriced_work.recorded',
  SUBCONTRACT_UNPRICED_WORK_CONVERTED: 'subcontract.unpriced_work.converted',
  SUBCONTRACT_UNPRICED_WORK_REJECTED: 'subcontract.unpriced_work.rejected',
  SUBCONTRACT_UNPRICED_WORK_CANCELLED: 'subcontract.unpriced_work.cancelled',
} as const;
