/**
 * Locale labels for profile-seeded vendor_category / vendor_specialty / cost_code keys.
 * Generated from profile-catalog-seeds; DB names stay English/Hebrew at seed time.
 */
import type { Locale } from '@/shared/i18n/config';
import { resolveLabelLocale } from '@/shared/i18n/intl-locale';

export const PROFILE_CATALOG_LABELS_EN: Readonly<Record<string, string>> = {
  building_materials: 'Building materials',
  equipment_rental: 'Equipment rental',
  concrete: 'Concrete',
  electrical: 'Electrical',
  plumbing: 'Plumbing',
  hvac: 'HVAC',
  finishes: 'Finishes',
  architect: 'Architect',
  engineer: 'Engineer',
  panels: 'Panels',
  lighting: 'Lighting',
  piping: 'Piping',
  '01': 'General requirements',
  '03': 'Concrete',
  '26': 'Electrical',
  '22': 'Plumbing',
  electrical_materials: 'Electrical materials',
  cable: 'Cable & wire',
  switchgear: 'Switchgear',
  electrical_sub: 'Electrical subcontractor',
  low_voltage: 'Low voltage',
  fire_alarm: 'Fire alarm',
  infrastructure: 'Infrastructure',
  'E-MAT': 'Electrical materials',
  'E-LAB': 'Electrical labor',
  'E-SUB': 'Electrical subcontract',
  drafting: 'Drafting',
  structural: 'Structural engineer',
  surveyor: 'Surveyor',
  print_shop: 'Print / plot',
  DES: 'Design fees',
  CONS: 'Consultants',
  parts: 'Spare parts',
  hvac_service: 'HVAC service',
  elevator: 'Elevator service',
  cleaning: 'Cleaning',
  PM: 'Preventive maintenance',
  CM: 'Corrective maintenance',
  general_supplier: 'General supplier',
  general_sub: 'General subcontractor',
  consultant: 'Consultant',
  service_provider: 'Service provider',
  plumbing_materials: 'Plumbing materials',
  plumbing_sub: 'Plumbing subcontractor',
  hvac_materials: 'HVAC materials',
  hvac_sub: 'HVAC subcontractor',
  lab_testing: 'Lab / testing',
  safety_equipment: 'Safety equipment',
  materials: 'Materials',
  lower_tier_sub: 'Lower-tier subcontractor',
};

export const PROFILE_CATALOG_LABELS_HE: Readonly<Record<string, string>> = {
  building_materials: 'חומרי בניין',
  equipment_rental: 'השכרת ציוד',
  concrete: 'בטון',
  electrical: 'חשמל',
  plumbing: 'אינסטלציה',
  hvac: 'מיזוג',
  finishes: 'גמרים',
  architect: 'אדריכל',
  engineer: 'מהנדס',
  panels: 'לוחות',
  lighting: 'תאורה',
  piping: 'צנרת',
  '01': 'דרישות כלליות',
  '03': 'בטון',
  '26': 'חשמל',
  '22': 'אינסטלציה',
  electrical_materials: 'חומרי חשמל',
  cable: 'כבלים',
  switchgear: 'לוחות ומפסקים',
  electrical_sub: 'קבלן חשמל',
  low_voltage: 'מתח נמוך',
  fire_alarm: 'גילוי אש',
  infrastructure: 'תשתית',
  'E-MAT': 'חומרי חשמל',
  'E-LAB': 'עבודת חשמל',
  'E-SUB': 'קבלנות חשמל',
  drafting: 'שרטוט',
  structural: 'מהנדס קונסטרוקציה',
  surveyor: 'מודד',
  print_shop: 'הדפסות',
  DES: 'שכר תכנון',
  CONS: 'יועצים',
  parts: 'חלקי חילוף',
  hvac_service: 'שירות מיזוג',
  elevator: 'מעליות',
  cleaning: 'ניקיון',
  PM: 'תחזוקה מונעת',
  CM: 'תיקון',
  general_supplier: 'ספק כללי',
  general_sub: 'קבלן משנה כללי',
  consultant: 'יועץ',
  service_provider: 'נותן שירות',
  plumbing_materials: 'חומרי אינסטלציה',
  plumbing_sub: 'קבלן אינסטלציה',
  hvac_materials: 'חומרי מיזוג',
  hvac_sub: 'קבלן מיזוג',
  lab_testing: 'מעבדה / בדיקות',
  safety_equipment: 'ציוד בטיחות',
  materials: 'חומרים',
  lower_tier_sub: 'קבלן משנה משני',
};

export const PROFILE_CATALOG_LABELS_AR: Readonly<Record<string, string>> = {
  building_materials: 'مواد بناء',
  equipment_rental: 'تأجير معدات',
  concrete: 'خرسانة',
  electrical: 'كهرباء',
  plumbing: 'سباكة',
  hvac: 'تكييف',
  finishes: 'تشطيبات',
  architect: 'مهندس معماري',
  engineer: 'مهندس',
  panels: 'لوحات',
  lighting: 'إضاءة',
  piping: 'أنابيب',
  '01': 'متطلبات عامة',
  '03': 'خرسانة',
  '26': 'كهرباء',
  '22': 'سباكة',
  electrical_materials: 'مواد كهربائية',
  cable: 'كابلات',
  switchgear: 'لوحات ومفاتيح',
  electrical_sub: 'مقاول كهرباء',
  low_voltage: 'جهد منخفض',
  fire_alarm: 'إنذار حريق',
  infrastructure: 'بنية تحتية',
  'E-MAT': 'مواد كهربائية',
  'E-LAB': 'عمل كهربائي',
  'E-SUB': 'مقاولات كهربائية',
  drafting: 'مسودات',
  structural: 'هندسة إنشائية',
  surveyor: 'مسّاح',
  print_shop: 'طباعة',
  DES: 'رسوم تصميم',
  CONS: 'استشاريون',
  parts: 'قطع غيار',
  hvac_service: 'خدمة تكييف',
  elevator: 'Elevator service',
  cleaning: 'Cleaning',
  PM: 'Preventive maintenance',
  CM: 'Corrective maintenance',
  general_supplier: 'General supplier',
  general_sub: 'General subcontractor',
  consultant: 'Consultant',
  service_provider: 'Service provider',
  plumbing_materials: 'Plumbing materials',
  plumbing_sub: 'Plumbing subcontractor',
  hvac_materials: 'HVAC materials',
  hvac_sub: 'HVAC subcontractor',
  lab_testing: 'Lab / testing',
  safety_equipment: 'Safety equipment',
  materials: 'مواد',
  lower_tier_sub: 'مقاول باطن من الدرجة الثانية',
};

export const PROFILE_CATALOG_LABELS_RU: Readonly<Record<string, string>> = {
  building_materials: 'Стройматериалы',
  equipment_rental: 'Аренда оборудования',
  concrete: 'Бетон',
  electrical: 'Электрика',
  plumbing: 'Сантехника',
  hvac: 'HVAC',
  finishes: 'Отделка',
  architect: 'Архитектор',
  engineer: 'Инженер',
  panels: 'Щиты',
  lighting: 'Освещение',
  piping: 'Трубопровод',
  '01': 'Общие требования',
  '03': 'Бетон',
  '26': 'Электрика',
  '22': 'Сантехника',
  electrical_materials: 'Электроматериалы',
  cable: 'Кабель',
  switchgear: 'Щиты и автоматы',
  electrical_sub: 'Субподрядчик по электрике',
  low_voltage: 'Слаботочные системы',
  fire_alarm: 'Пожарная сигнализация',
  infrastructure: 'Инфраструктура',
  'E-MAT': 'Электроматериалы',
  'E-LAB': 'Электромонтаж',
  'E-SUB': 'Субподряд электрики',
  drafting: 'Черчение',
  structural: 'Кonstruktivный инженер',
  surveyor: 'Геодезист',
  print_shop: 'Печать',
  DES: 'Проектирование',
  CONS: 'Консультанты',
  parts: 'Запчасти',
  hvac_service: 'Сервис HVAC',
  elevator: 'Elevator service',
  cleaning: 'Cleaning',
  PM: 'Preventive maintenance',
  CM: 'Corrective maintenance',
  general_supplier: 'General supplier',
  general_sub: 'General subcontractor',
  consultant: 'Consultant',
  service_provider: 'Service provider',
  plumbing_materials: 'Plumbing materials',
  plumbing_sub: 'Plumbing subcontractor',
  hvac_materials: 'HVAC materials',
  hvac_sub: 'HVAC subcontractor',
  lab_testing: 'Lab / testing',
  safety_equipment: 'Safety equipment',
  materials: 'Материалы',
  lower_tier_sub: 'Субподрядчик нижнего уровня',
};

const LABELS_BY_LOCALE: Readonly<Record<Locale, Readonly<Record<string, string>>>> = {
  en: PROFILE_CATALOG_LABELS_EN,
  'he-IL': PROFILE_CATALOG_LABELS_HE,
  ar: PROFILE_CATALOG_LABELS_AR,
  ru: PROFILE_CATALOG_LABELS_RU,
};

export function localizeProfileCatalogName(
  key: string | null | undefined,
  fallbackName: string,
  locale: string,
  isSystem = true,
): string {
  if (!key || !isSystem) return fallbackName;
  const labels = LABELS_BY_LOCALE[resolveLabelLocale(locale)];
  return labels[key] ?? fallbackName;
}

export function localizeProfileCatalogOptions(
  entries: readonly { id: string; key: string; name: string; isSystem?: boolean }[],
  locale: string,
): Array<{ id: string; name: string; key?: string }> {
  return entries.map((entry) => ({
    id: entry.id,
    key: entry.key,
    name: localizeProfileCatalogName(entry.key, entry.name, locale, entry.isSystem ?? false),
  }));
}