/** Audit actions for the 'field' track (Developer/GC build). Shape: entity.verb. Labels go in settings.activity.actions (4 locales). */
export const FIELD_AUDIT_ACTIONS = {
  SITE_DAILY_LOG_CREATED: 'site_daily_log.created',
  SITE_DAILY_LOG_UPDATED: 'site_daily_log.updated',
  SITE_DAILY_LOG_CLOSED: 'site_daily_log.closed',
  SITE_DAILY_LOG_REOPENED: 'site_daily_log.reopened',
  SITE_DAILY_LOG_ENTRY_ADDED: 'site_daily_log.entry_added',
  SITE_DAILY_LOG_ENTRY_UPDATED: 'site_daily_log.entry_updated',
  SITE_DAILY_LOG_ENTRY_REMOVED: 'site_daily_log.entry_removed',
  SITE_DAILY_REPORT_SUBMITTED: 'site_daily_report.submitted',
  SITE_MEETING_CREATED: 'site_meeting.created',
  SITE_MEETING_UPDATED: 'site_meeting.updated',
  SITE_MEETING_HELD: 'site_meeting.held',
  SITE_MEETING_CANCELLED: 'site_meeting.cancelled',
  SITE_MEETING_PUBLISHED: 'site_meeting.published',
  SITE_MEETING_ATTENDEE_ADDED: 'site_meeting.attendee_added',
  SITE_MEETING_ATTENDEE_REMOVED: 'site_meeting.attendee_removed',
  SITE_MEETING_DECISION_RECORDED: 'site_meeting.decision_recorded',
  SITE_MEETING_ACTION_ITEM_CREATED: 'site_meeting.action_item_created',
  SITE_INSTRUCTION_ISSUED: 'site_instruction.issued',
  SITE_INSTRUCTION_UPDATED: 'site_instruction.updated',
  SITE_INSTRUCTION_ACKNOWLEDGED: 'site_instruction.acknowledged',
  SITE_INSTRUCTION_PERFORMED: 'site_instruction.performed',
  SITE_INSTRUCTION_CLOSED: 'site_instruction.closed',
  SITE_INSTRUCTION_CANCELLED: 'site_instruction.cancelled',
  SITE_INSTRUCTION_REOPENED: 'site_instruction.reopened',
  SITE_INSTRUCTION_CONVERSION_REQUESTED: 'site_instruction.conversion_requested',
  SITE_INSTRUCTION_CONVERTED: 'site_instruction.converted',
  SITE_INSTRUCTION_CONVERSION_DISMISSED: 'site_instruction.conversion_dismissed',
} as const;
