import { PROJECT_CAPABILITIES as C } from '@/modules/project-team/domain/capabilities';
import { EXTERNAL_CAPABILITIES as X } from '@/shared/external/capabilities';
import {
  agreement,
  internalProjectLink,
  internalTaskLink,
  payloadDate,
  payloadSegment,
  portalProjectLink,
  subject,
} from './deep-links';
import type { DgEventSpec, DomainEventRecord } from './types';

/**
 * Domain event -> notification mapping for every event named in the track briefs (section 3).
 *
 * Payload conventions the consumer understands (all optional, ids only - never money):
 *   vendorId, agreementId | subcontractAgreementId   single contractor scope
 *   vendorIds[], targets[{ vendorId, agreementId }]  multi-contractor scope (events, meetings, shares)
 *   allProjectContractors: true                      every contractor that can see the project
 *   reference                                        short human reference (number / code)
 *   plus the per-event named recipient keys listed below.
 * When no vendor scope is in the payload, the consumer asks `resolveEntityScope` for it.
 */

const byExternalActor = (event: DomainEventRecord) => event.actorType === 'external';
const byInternalActor = (event: DomainEventRecord) => event.actorType !== 'external';
const contractorAudience = (event: DomainEventRecord) => event.payload.audience !== 'internal';
const contractorVisible = (event: DomainEventRecord) => event.payload.contractorVisible === true;

function reviewOutcomeSeverity(event: DomainEventRecord): 'info' | 'warning' {
  const status = event.payload.status ?? event.payload.outcome;
  return status === 'revise_and_resubmit' || status === 'rejected' ? 'warning' : 'info';
}

const SPECS: readonly DgEventSpec[] = [
  // ── Subcontract core (track E) ────────────────────────────────────────────
  {
    type: 'subcontract.change.submitted',
    category: 'dg_contract',
    financial: true,
    severity: 'warning',
    internal: { capabilities: [C.CHANGE_FINANCIAL_MANAGE] },
    internalLink: (i) => internalProjectLink(i, 'contractors', agreement(i), 'changes'),
    portalLink: (i) => portalProjectLink(i, 'contracts', agreement(i), 'changes'),
  },
  {
    type: 'subcontract.change.approved',
    category: 'dg_contract',
    financial: true,
    severity: 'info',
    internal: { capabilities: [C.CONTRACT_FINANCIAL_VIEW], when: byExternalActor },
    external: { capabilities: [X.CHANGE_REQUEST] },
    internalLink: (i) => internalProjectLink(i, 'contractors', agreement(i), 'changes'),
    portalLink: (i) => portalProjectLink(i, 'contracts', agreement(i), 'changes'),
    resolves: ['subcontract.change.submitted'],
  },
  {
    type: 'subcontract.change.rejected',
    category: 'dg_contract',
    financial: true,
    severity: 'warning',
    internal: { capabilities: [C.CONTRACT_FINANCIAL_VIEW], when: byExternalActor },
    external: { capabilities: [X.CHANGE_REQUEST] },
    internalLink: (i) => internalProjectLink(i, 'contractors', agreement(i), 'changes'),
    portalLink: (i) => portalProjectLink(i, 'contracts', agreement(i), 'changes'),
    resolves: ['subcontract.change.submitted'],
  },
  {
    type: 'subcontract.agreement.activated',
    category: 'dg_contract',
    financial: false,
    severity: 'info',
    internal: { capabilities: [C.CONTRACTOR_COORDINATE] },
    external: { capabilities: [X.PROJECT_VIEW] },
    internalLink: (i) => internalProjectLink(i, 'contractors', agreement(i) ?? subject(i)),
    portalLink: (i) => portalProjectLink(i, 'contracts', agreement(i) ?? subject(i)),
  },

  // ── Claims (track F) - financial only ─────────────────────────────────────
  {
    type: 'subcontract.claim.submitted',
    category: 'dg_claim',
    financial: true,
    severity: 'warning',
    internal: { capabilities: [C.CLAIM_REVIEW], namedPayloadKeys: ['reviewerUserId'] },
    internalLink: (i) => internalProjectLink(i, 'claims', subject(i)),
    portalLink: (i) => portalProjectLink(i, 'claims', subject(i)),
  },
  {
    type: 'subcontract.claim.returned',
    category: 'dg_claim',
    financial: true,
    severity: 'warning',
    external: { capabilities: [X.CLAIM_VIEW] },
    internalLink: (i) => internalProjectLink(i, 'claims', subject(i)),
    portalLink: (i) => portalProjectLink(i, 'claims', subject(i)),
    resolves: ['subcontract.claim.submitted'],
  },
  {
    type: 'subcontract.claim.certified',
    category: 'dg_claim',
    financial: true,
    severity: 'info',
    internal: { capabilities: [C.PAYMENT_MANAGE] },
    external: { capabilities: [X.CLAIM_VIEW] },
    internalLink: (i) => internalProjectLink(i, 'claims', subject(i)),
    portalLink: (i) => portalProjectLink(i, 'claims', subject(i)),
    resolves: ['subcontract.claim.submitted', 'subcontract.claim.returned'],
  },
  {
    type: 'subcontract.claim.reassessed',
    category: 'dg_claim',
    financial: true,
    severity: 'info',
    external: { capabilities: [X.CLAIM_VIEW] },
    internalLink: (i) => internalProjectLink(i, 'claims', subject(i)),
    portalLink: (i) => portalProjectLink(i, 'claims', subject(i)),
    resolves: ['subcontract.claim.submitted'],
  },
  {
    type: 'subcontract.deduction.issued',
    category: 'dg_claim',
    financial: true,
    severity: 'warning',
    external: { capabilities: [X.CLAIM_VIEW], when: contractorVisible },
    internalLink: (i) => internalProjectLink(i, 'deductions'),
    portalLink: (i) => portalProjectLink(i, 'payments'),
  },

  // ── Contractor tasks / collaboration (track G) ────────────────────────────
  {
    type: 'task.external.assigned',
    category: 'dg_task',
    financial: false,
    severity: 'warning',
    external: { capabilities: [X.TASK_WORK], namedPayloadKeys: ['assigneePrincipalId'] },
    internalLink: internalTaskLink,
    portalLink: (i) => portalProjectLink(i, 'tasks', subject(i)),
  },
  {
    type: 'task.external.acknowledged',
    category: 'dg_task',
    financial: false,
    severity: 'info',
    internal: {
      capabilities: [C.TASKS_MANAGE],
      namedPayloadKeys: ['assignedByUserId', 'createdByUserId'],
      namedOnly: true,
    },
    internalLink: internalTaskLink,
    portalLink: (i) => portalProjectLink(i, 'tasks', subject(i)),
    resolves: ['task.external.assigned'],
  },
  {
    type: 'task.external.completion_submitted',
    category: 'dg_task',
    financial: false,
    severity: 'warning',
    internal: { capabilities: [C.TASKS_MANAGE], namedPayloadKeys: ['verifierUserId', 'assignedByUserId'] },
    internalLink: internalTaskLink,
    portalLink: (i) => portalProjectLink(i, 'tasks', subject(i)),
    resolves: ['task.external.assigned', 'task.external.reopened'],
  },
  {
    type: 'task.external.verified',
    category: 'dg_task',
    financial: false,
    severity: 'info',
    external: { capabilities: [X.TASK_WORK], namedPayloadKeys: ['assigneePrincipalId'] },
    internalLink: internalTaskLink,
    portalLink: (i) => portalProjectLink(i, 'tasks', subject(i)),
    resolves: ['task.external.completion_submitted'],
  },
  {
    type: 'task.external.reopened',
    category: 'dg_task',
    financial: false,
    severity: 'warning',
    external: { capabilities: [X.TASK_WORK], namedPayloadKeys: ['assigneePrincipalId'] },
    internalLink: internalTaskLink,
    portalLink: (i) => portalProjectLink(i, 'tasks', subject(i)),
  },
  {
    type: 'collab.comment.posted',
    category: 'dg_task',
    financial: false,
    severity: 'info',
    subjectPayloadKey: 'targetEntityId',
    internal: {
      capabilities: [C.CONTRACTOR_COORDINATE],
      namedPayloadKeys: ['mentionedUserIds', 'participantUserIds'],
      namedOnly: true,
    },
    external: { capabilities: [X.THREAD_POST], when: (e) => contractorAudience(e) && byInternalActor(e) },
    internalLink: (i) => internalProjectLink(i, 'activity'),
    portalLink: (i) => portalProjectLink(i),
  },

  // ── Coordination events (track H) ─────────────────────────────────────────
  {
    type: 'coordination.event.created',
    category: 'dg_coordination',
    financial: false,
    severity: 'info',
    external: { capabilities: [X.SCHEDULE_VIEW] },
    internalLink: (i) => internalProjectLink(i, 'coordination', subject(i)),
    portalLink: (i) => portalProjectLink(i, 'events', subject(i)),
  },
  {
    type: 'coordination.event.rescheduled',
    category: 'dg_coordination',
    financial: false,
    severity: 'warning',
    internal: { capabilities: [C.SCHEDULE_VIEW], namedPayloadKeys: ['participantUserIds'], namedOnly: true },
    external: { capabilities: [X.SCHEDULE_VIEW] },
    internalLink: (i) => internalProjectLink(i, 'coordination', subject(i)),
    portalLink: (i) => portalProjectLink(i, 'events', subject(i)),
  },
  {
    type: 'coordination.event.completed',
    category: 'dg_coordination',
    financial: false,
    severity: 'info',
    internal: { capabilities: [C.SCHEDULE_VIEW], namedPayloadKeys: ['participantUserIds'], namedOnly: true },
    external: { capabilities: [X.SCHEDULE_VIEW] },
    internalLink: (i) => internalProjectLink(i, 'coordination', subject(i)),
    portalLink: (i) => portalProjectLink(i, 'events', subject(i)),
    resolves: ['coordination.readiness.requested', 'coordination.contractor.not_ready'],
  },
  {
    type: 'coordination.event.cancelled',
    category: 'dg_coordination',
    financial: false,
    severity: 'warning',
    internal: { capabilities: [C.SCHEDULE_VIEW], namedPayloadKeys: ['participantUserIds'], namedOnly: true },
    external: { capabilities: [X.SCHEDULE_VIEW] },
    internalLink: (i) => internalProjectLink(i, 'coordination', subject(i)),
    portalLink: (i) => portalProjectLink(i, 'events', subject(i)),
    resolves: [
      'coordination.event.created',
      'coordination.readiness.requested',
      'coordination.contractor.not_ready',
      'coordination.contractor.ready',
    ],
  },
  {
    type: 'coordination.readiness.requested',
    category: 'dg_coordination',
    financial: false,
    severity: 'warning',
    subjectPayloadKey: 'eventId',
    external: { capabilities: [X.EVENT_RESPOND] },
    internalLink: (i) => internalProjectLink(i, 'coordination', subject(i)),
    portalLink: (i) => portalProjectLink(i, 'events', subject(i)),
  },
  {
    type: 'coordination.contractor.ready',
    category: 'dg_coordination',
    financial: false,
    severity: 'info',
    subjectPayloadKey: 'eventId',
    internal: { capabilities: [C.SCHEDULE_MANAGE], namedPayloadKeys: ['organizerUserId'] },
    internalLink: (i) => internalProjectLink(i, 'coordination', subject(i)),
    portalLink: (i) => portalProjectLink(i, 'events', subject(i)),
    resolves: ['coordination.contractor.not_ready'],
  },
  {
    type: 'coordination.contractor.not_ready',
    category: 'dg_coordination',
    financial: false,
    severity: 'urgent',
    subjectPayloadKey: 'eventId',
    internal: { capabilities: [C.SCHEDULE_MANAGE], namedPayloadKeys: ['organizerUserId'] },
    internalLink: (i) => internalProjectLink(i, 'coordination', subject(i)),
    portalLink: (i) => portalProjectLink(i, 'events', subject(i)),
    resolves: ['coordination.contractor.ready'],
  },
  {
    type: 'coordination.event.ready',
    category: 'dg_coordination',
    financial: false,
    severity: 'info',
    internal: { capabilities: [C.SCHEDULE_MANAGE], namedPayloadKeys: ['organizerUserId', 'participantUserIds'] },
    internalLink: (i) => internalProjectLink(i, 'coordination', subject(i)),
    portalLink: (i) => portalProjectLink(i, 'events', subject(i)),
    resolves: ['coordination.contractor.not_ready'],
  },

  // ── Documents / plans (track IJ) ──────────────────────────────────────────
  {
    type: 'plan.revision.published',
    category: 'dg_document',
    financial: false,
    severity: 'warning',
    subjectPayloadKey: 'drawingId',
    internal: { capabilities: [C.DOCUMENTS_VIEW], namedPayloadKeys: ['distributionUserIds'], namedOnly: true },
    external: { capabilities: [X.PLAN_VIEW] },
    internalLink: (i) => internalProjectLink(i, 'plans', subject(i)),
    portalLink: (i) => portalProjectLink(i, 'plans', subject(i)),
  },
  {
    type: 'document.shared',
    category: 'dg_document',
    financial: false,
    severity: 'info',
    external: { capabilities: [X.DOCUMENT_VIEW], namedPayloadKeys: ['principalIds'] },
    internalLink: (i) => internalProjectLink(i),
    portalLink: (i) => portalProjectLink(i, 'documents'),
  },
  {
    type: 'plan.revision.acknowledged',
    category: 'dg_document',
    financial: false,
    severity: 'info',
    subjectPayloadKey: 'drawingId',
    internal: { capabilities: [C.DOCUMENTS_SHARE], namedPayloadKeys: ['publishedByUserId'] },
    internalLink: (i) => internalProjectLink(i, 'plans', subject(i)),
    portalLink: (i) => portalProjectLink(i, 'plans', subject(i)),
  },

  // ── RFI / submittals (track KL) ───────────────────────────────────────────
  {
    type: 'rfi.request.submitted',
    category: 'dg_rfi',
    financial: false,
    severity: 'warning',
    internal: { capabilities: [C.RFI_MANAGE], namedPayloadKeys: ['assigneeUserId'] },
    internalLink: (i) => internalProjectLink(i, 'rfi', subject(i)),
    portalLink: (i) => portalProjectLink(i, 'rfi', subject(i)),
  },
  {
    type: 'rfi.request.answered',
    category: 'dg_rfi',
    financial: false,
    severity: 'info',
    internal: { capabilities: [C.RFI_MANAGE], namedPayloadKeys: ['raisedByUserId'], namedOnly: true },
    external: { capabilities: [X.RFI_RAISE] },
    internalLink: (i) => internalProjectLink(i, 'rfi', subject(i)),
    portalLink: (i) => portalProjectLink(i, 'rfi', subject(i)),
    resolves: ['rfi.request.submitted'],
  },
  {
    type: 'rfi.request.closed',
    category: 'dg_rfi',
    financial: false,
    severity: 'info',
    external: { capabilities: [X.RFI_RAISE] },
    internalLink: (i) => internalProjectLink(i, 'rfi', subject(i)),
    portalLink: (i) => portalProjectLink(i, 'rfi', subject(i)),
    resolves: ['rfi.request.submitted', 'rfi.request.answered'],
  },
  {
    type: 'submittal.package.submitted',
    category: 'dg_rfi',
    financial: false,
    severity: 'warning',
    internal: { capabilities: [C.SUBMITTAL_MANAGE], namedPayloadKeys: ['reviewerUserId'] },
    internalLink: (i) => internalProjectLink(i, 'submittals', subject(i)),
    portalLink: (i) => portalProjectLink(i, 'submittals', subject(i)),
  },
  {
    type: 'submittal.package.reviewed',
    category: 'dg_rfi',
    financial: false,
    severity: reviewOutcomeSeverity,
    external: { capabilities: [X.SUBMITTAL_SUBMIT] },
    internalLink: (i) => internalProjectLink(i, 'submittals', subject(i)),
    portalLink: (i) => portalProjectLink(i, 'submittals', subject(i)),
    resolves: ['submittal.package.submitted'],
  },

  // ── Inspections / defects (track MN) ──────────────────────────────────────
  {
    type: 'quality.inspection.completed',
    category: 'dg_quality',
    financial: false,
    severity: 'info',
    external: { capabilities: [X.INSPECTION_VIEW] },
    internalLink: (i) => internalProjectLink(i, 'inspections', subject(i)),
    portalLink: (i) => portalProjectLink(i, 'inspections'),
  },
  {
    type: 'quality.inspection.failed',
    category: 'dg_quality',
    financial: false,
    severity: 'warning',
    internal: { capabilities: [C.QUALITY_MANAGE] },
    external: { capabilities: [X.INSPECTION_VIEW] },
    internalLink: (i) => internalProjectLink(i, 'inspections', subject(i)),
    portalLink: (i) => portalProjectLink(i, 'inspections'),
  },
  {
    type: 'defect.item.opened',
    category: 'dg_quality',
    financial: false,
    severity: 'warning',
    internal: { capabilities: [C.DEFECTS_MANAGE], when: byExternalActor },
    external: { capabilities: [X.DEFECT_WORK] },
    internalLink: (i) => internalProjectLink(i, 'defects', subject(i)),
    portalLink: (i) => portalProjectLink(i, 'defects', subject(i)),
  },
  {
    type: 'defect.item.assigned',
    category: 'dg_quality',
    financial: false,
    severity: 'warning',
    external: { capabilities: [X.DEFECT_WORK], namedPayloadKeys: ['assigneePrincipalId'] },
    internalLink: (i) => internalProjectLink(i, 'defects', subject(i)),
    portalLink: (i) => portalProjectLink(i, 'defects', subject(i)),
  },
  {
    type: 'defect.completion_submitted',
    category: 'dg_quality',
    financial: false,
    severity: 'warning',
    internal: { capabilities: [C.DEFECTS_MANAGE], namedPayloadKeys: ['inspectorUserId'] },
    internalLink: (i) => internalProjectLink(i, 'defects', subject(i)),
    portalLink: (i) => portalProjectLink(i, 'defects', subject(i)),
    resolves: ['defect.item.assigned', 'defect.item.reopened', 'defect.item.opened'],
  },
  {
    type: 'defect.item.completion_submitted',
    category: 'dg_quality',
    financial: false,
    severity: 'warning',
    internal: { capabilities: [C.DEFECTS_MANAGE], namedPayloadKeys: ['inspectorUserId'] },
    internalLink: (i) => internalProjectLink(i, 'defects', subject(i)),
    portalLink: (i) => portalProjectLink(i, 'defects', subject(i)),
    resolves: ['defect.item.assigned', 'defect.item.reopened', 'defect.item.opened'],
  },
  {
    type: 'defect.item.closed',
    category: 'dg_quality',
    financial: false,
    severity: 'info',
    external: { capabilities: [X.DEFECT_WORK] },
    internalLink: (i) => internalProjectLink(i, 'defects', subject(i)),
    portalLink: (i) => portalProjectLink(i, 'defects', subject(i)),
    resolves: [
      'defect.item.opened',
      'defect.item.assigned',
      'defect.item.reopened',
      'defect.completion_submitted',
      'defect.item.completion_submitted',
    ],
  },
  {
    type: 'defect.item.reopened',
    category: 'dg_quality',
    financial: false,
    severity: 'warning',
    external: { capabilities: [X.DEFECT_WORK], namedPayloadKeys: ['assigneePrincipalId'] },
    internalLink: (i) => internalProjectLink(i, 'defects', subject(i)),
    portalLink: (i) => portalProjectLink(i, 'defects', subject(i)),
    resolves: ['defect.completion_submitted', 'defect.item.completion_submitted'],
  },

  // ── Daily log / meetings / instructions (track O) ─────────────────────────
  {
    type: 'field.daily_log.submitted',
    category: 'dg_field',
    financial: false,
    severity: 'info',
    internal: { capabilities: [C.DAILY_LOG_MANAGE], when: byExternalActor },
    internalLink: (i) => internalProjectLink(i, 'site-log', payloadDate(i, 'logDate')),
    portalLink: (i) => portalProjectLink(i, 'site-log'),
  },
  {
    type: 'field.instruction.issued',
    category: 'dg_field',
    financial: false,
    severity: (e) => (e.payload.urgent === true || e.payload.kind === 'urgent_before_price' ? 'urgent' : 'warning'),
    external: { capabilities: [X.SITE_INSTRUCTION_ACK] },
    internalLink: (i) => internalProjectLink(i, 'instructions', subject(i)),
    portalLink: (i) => portalProjectLink(i, 'instructions', subject(i)),
  },
  {
    type: 'field.instruction.acknowledged',
    category: 'dg_field',
    financial: false,
    severity: 'info',
    internal: { capabilities: [C.CONTRACTOR_COORDINATE], namedPayloadKeys: ['issuedByUserId'] },
    internalLink: (i) => internalProjectLink(i, 'instructions', subject(i)),
    portalLink: (i) => portalProjectLink(i, 'instructions', subject(i)),
  },
  {
    type: 'field.meeting.published',
    category: 'dg_field',
    financial: false,
    severity: 'info',
    internal: { capabilities: [C.MEETINGS_MANAGE], namedPayloadKeys: ['attendeeUserIds'], namedOnly: true },
    external: { capabilities: [X.PROJECT_VIEW] },
    internalLink: (i) => internalProjectLink(i, 'site-meetings', subject(i)),
    portalLink: (i) => portalProjectLink(i),
  },

  // ── Compliance / safety / deliveries (track P) ────────────────────────────
  {
    type: 'compliance.document.expiring',
    category: 'dg_compliance',
    financial: false,
    severity: 'warning',
    internal: { capabilities: [C.CONTRACTOR_COORDINATE] },
    external: { capabilities: [X.COMPLIANCE_SUBMIT] },
    internalLink: (i) => internalProjectLink(i, 'contractor-compliance'),
    portalLink: (i) => portalProjectLink(i, 'compliance'),
  },
  {
    type: 'compliance.document.expired',
    category: 'dg_compliance',
    financial: false,
    severity: 'urgent',
    internal: { capabilities: [C.CONTRACTOR_COORDINATE] },
    external: { capabilities: [X.COMPLIANCE_SUBMIT] },
    internalLink: (i) => internalProjectLink(i, 'contractor-compliance'),
    portalLink: (i) => portalProjectLink(i, 'compliance'),
    resolves: ['compliance.document.expiring'],
  },
  {
    type: 'compliance.document.submitted',
    category: 'dg_compliance',
    financial: false,
    severity: 'info',
    internal: { capabilities: [C.CONTRACTOR_COORDINATE], when: byExternalActor },
    internalLink: (i) => internalProjectLink(i, 'contractor-compliance'),
    portalLink: (i) => portalProjectLink(i, 'compliance'),
    resolves: ['compliance.document.expiring', 'compliance.document.expired'],
  },
  {
    type: 'safety.record.reported',
    category: 'dg_compliance',
    financial: false,
    severity: (e) => (e.payload.kind === 'incident' ? 'urgent' : 'warning'),
    internal: { capabilities: [C.SAFETY_MANAGE] },
    external: { capabilities: [X.SAFETY_REPORT], when: byInternalActor },
    internalLink: (i) => internalProjectLink(i, 'site-safety'),
    portalLink: (i) => portalProjectLink(i, 'safety'),
  },
  {
    type: 'safety.record.closed',
    category: 'dg_compliance',
    financial: false,
    severity: 'info',
    external: { capabilities: [X.SAFETY_REPORT] },
    internalLink: (i) => internalProjectLink(i, 'site-safety'),
    portalLink: (i) => portalProjectLink(i, 'safety'),
    resolves: ['safety.record.reported'],
  },
  {
    type: 'delivery.item.delayed',
    category: 'dg_compliance',
    financial: false,
    severity: 'warning',
    internal: { capabilities: [C.SCHEDULE_MANAGE] },
    external: { capabilities: [X.DELIVERY_REPORT], when: byInternalActor },
    internalLink: (i) => internalProjectLink(i, 'deliveries'),
    portalLink: (i) => portalProjectLink(i, 'deliveries'),
  },
  {
    type: 'delivery.item.delivered',
    category: 'dg_compliance',
    financial: false,
    severity: 'info',
    internal: { capabilities: [C.SCHEDULE_MANAGE], when: byExternalActor },
    internalLink: (i) => internalProjectLink(i, 'deliveries'),
    portalLink: (i) => portalProjectLink(i, 'deliveries'),
    resolves: ['delivery.item.delayed'],
  },

  // ── Procurement / closeout / warranty (track Q) ───────────────────────────
  {
    type: 'procurement.tender.awarded',
    category: 'dg_procurement',
    financial: true,
    severity: 'info',
    internal: { capabilities: [C.CONTRACT_MANAGE] },
    external: { capabilities: [X.BID_SUBMIT] },
    internalLink: (i) => internalProjectLink(i, 'tenders', subject(i)),
    portalLink: (i) => portalProjectLink(i, 'tenders'),
  },
  {
    type: 'closeout.agreement.closed',
    category: 'dg_procurement',
    financial: false,
    severity: 'info',
    internal: { capabilities: [C.CONTRACTOR_COORDINATE] },
    external: { capabilities: [X.HANDOVER_SUBMIT] },
    internalLink: (i) => internalProjectLink(i, 'contractor-closeout'),
    portalLink: (i) => portalProjectLink(i, 'handover'),
  },
  {
    type: 'warranty.claim.reported',
    category: 'dg_procurement',
    financial: false,
    severity: 'warning',
    internal: { capabilities: [C.DEFECTS_MANAGE], when: byExternalActor },
    external: { capabilities: [X.DEFECT_WORK], when: byInternalActor },
    internalLink: (i) => internalProjectLink(i, 'contractor-warranty'),
    portalLink: (i) => portalProjectLink(i, 'defects', payloadSegment(i, 'defectId')),
  },
];

export const DG_EVENT_SPECS: readonly DgEventSpec[] = SPECS;

const SPEC_BY_TYPE = new Map(SPECS.map((spec) => [spec.type, spec] as const));

export function findDgEventSpec(eventType: string): DgEventSpec | undefined {
  return SPEC_BY_TYPE.get(eventType);
}

/** Locale copy key: `subcontract.claim.submitted` -> `subcontract_claim_submitted`. */
export function dgCopyKey(eventType: string): string {
  return eventType.replaceAll('.', '_');
}
